/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiTestIndexRouteImport } from './routes/ui-test/index'
import { Route as SurveysIndexRouteImport } from './routes/surveys/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProjectsSlugIndexRouteImport } from './routes/projects/$slug/index'
import { Route as ProjectsSlugSurveysRouteImport } from './routes/projects/$slug/surveys'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiTestIndexRoute = UiTestIndexRouteImport.update({
  id: '/ui-test/',
  path: '/ui-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIndexRoute = SurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugIndexRoute = ProjectsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugSurveysRoute = ProjectsSlugSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => ProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/ui-test/': typeof UiTestIndexRoute
  '/projects/$slug/surveys': typeof ProjectsSlugSurveysRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/surveys': typeof SurveysIndexRoute
  '/ui-test': typeof UiTestIndexRoute
  '/projects/$slug/surveys': typeof ProjectsSlugSurveysRoute
  '/projects/$slug': typeof ProjectsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/ui-test/': typeof UiTestIndexRoute
  '/projects/$slug/surveys': typeof ProjectsSlugSurveysRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$slug'
    | '/projects/'
    | '/surveys/'
    | '/ui-test/'
    | '/projects/$slug/surveys'
    | '/projects/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/surveys'
    | '/ui-test'
    | '/projects/$slug/surveys'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/projects/$slug'
    | '/projects/'
    | '/surveys/'
    | '/ui-test/'
    | '/projects/$slug/surveys'
    | '/projects/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SurveysIndexRoute: typeof SurveysIndexRoute
  UiTestIndexRoute: typeof UiTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-test/': {
      id: '/ui-test/'
      path: '/ui-test'
      fullPath: '/ui-test/'
      preLoaderRoute: typeof UiTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/': {
      id: '/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof SurveysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/': {
      id: '/projects/$slug/'
      path: '/'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof ProjectsSlugIndexRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/surveys': {
      id: '/projects/$slug/surveys'
      path: '/surveys'
      fullPath: '/projects/$slug/surveys'
      preLoaderRoute: typeof ProjectsSlugSurveysRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
  }
}

interface ProjectsSlugRouteChildren {
  ProjectsSlugSurveysRoute: typeof ProjectsSlugSurveysRoute
  ProjectsSlugIndexRoute: typeof ProjectsSlugIndexRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugSurveysRoute: ProjectsSlugSurveysRoute,
  ProjectsSlugIndexRoute: ProjectsSlugIndexRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SurveysIndexRoute: SurveysIndexRoute,
  UiTestIndexRoute: UiTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
