/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiTestIndexRouteImport } from './routes/ui-test/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProjectsSlugIndexRouteImport } from './routes/projects/$slug/index'
import { Route as ProjectsSlugSurveysRouteImport } from './routes/projects/$slug/surveys'
import { Route as ProjectsSlugSettingsRouteImport } from './routes/projects/$slug/settings'
import { Route as ProjectsSlugRolesRouteImport } from './routes/projects/$slug/roles'
import { Route as ProjectsSlugMembersRouteImport } from './routes/projects/$slug/members'
import { Route as ProjectsSlugManagementRouteImport } from './routes/projects/$slug/management'
import { Route as ProjectsSlugSurveySlugRouteImport } from './routes/projects/$slug/$surveySlug'
import { Route as ProjectsSlugSurveySlugIndexRouteImport } from './routes/projects/$slug/$surveySlug/index'
import { Route as ProjectsSlugSurveySlugVersionsRouteImport } from './routes/projects/$slug/$surveySlug/versions'
import { Route as ProjectsSlugSurveySlugSettingsRouteImport } from './routes/projects/$slug/$surveySlug/settings'
import { Route as ProjectsSlugSurveySlugResponsesRouteImport } from './routes/projects/$slug/$surveySlug/responses'
import { Route as ProjectsSlugSurveySlugOverviewRouteImport } from './routes/projects/$slug/$surveySlug/overview'
import { Route as ProjectsSlugSurveySlugMembersRouteImport } from './routes/projects/$slug/$surveySlug/members'
import { Route as ProjectsSlugSurveySlugLinksRouteImport } from './routes/projects/$slug/$surveySlug/links'
import { Route as ProjectsSlugSurveySlugBuilderRouteImport } from './routes/projects/$slug/$surveySlug/builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiTestIndexRoute = UiTestIndexRouteImport.update({
  id: '/ui-test/',
  path: '/ui-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugIndexRoute = ProjectsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugSurveysRoute = ProjectsSlugSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugSettingsRoute = ProjectsSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugRolesRoute = ProjectsSlugRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugMembersRoute = ProjectsSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugManagementRoute = ProjectsSlugManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugSurveySlugRoute = ProjectsSlugSurveySlugRouteImport.update({
  id: '/$surveySlug',
  path: '/$surveySlug',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugSurveySlugIndexRoute =
  ProjectsSlugSurveySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)
const ProjectsSlugSurveySlugVersionsRoute =
  ProjectsSlugSurveySlugVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)
const ProjectsSlugSurveySlugSettingsRoute =
  ProjectsSlugSurveySlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)
const ProjectsSlugSurveySlugResponsesRoute =
  ProjectsSlugSurveySlugResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)
const ProjectsSlugSurveySlugOverviewRoute =
  ProjectsSlugSurveySlugOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)
const ProjectsSlugSurveySlugMembersRoute =
  ProjectsSlugSurveySlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)
const ProjectsSlugSurveySlugLinksRoute =
  ProjectsSlugSurveySlugLinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)
const ProjectsSlugSurveySlugBuilderRoute =
  ProjectsSlugSurveySlugBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => ProjectsSlugSurveySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/ui-test/': typeof UiTestIndexRoute
  '/projects/$slug/$surveySlug': typeof ProjectsSlugSurveySlugRouteWithChildren
  '/projects/$slug/management': typeof ProjectsSlugManagementRoute
  '/projects/$slug/members': typeof ProjectsSlugMembersRoute
  '/projects/$slug/roles': typeof ProjectsSlugRolesRoute
  '/projects/$slug/settings': typeof ProjectsSlugSettingsRoute
  '/projects/$slug/surveys': typeof ProjectsSlugSurveysRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
  '/projects/$slug/$surveySlug/builder': typeof ProjectsSlugSurveySlugBuilderRoute
  '/projects/$slug/$surveySlug/links': typeof ProjectsSlugSurveySlugLinksRoute
  '/projects/$slug/$surveySlug/members': typeof ProjectsSlugSurveySlugMembersRoute
  '/projects/$slug/$surveySlug/overview': typeof ProjectsSlugSurveySlugOverviewRoute
  '/projects/$slug/$surveySlug/responses': typeof ProjectsSlugSurveySlugResponsesRoute
  '/projects/$slug/$surveySlug/settings': typeof ProjectsSlugSurveySlugSettingsRoute
  '/projects/$slug/$surveySlug/versions': typeof ProjectsSlugSurveySlugVersionsRoute
  '/projects/$slug/$surveySlug/': typeof ProjectsSlugSurveySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/ui-test': typeof UiTestIndexRoute
  '/projects/$slug/management': typeof ProjectsSlugManagementRoute
  '/projects/$slug/members': typeof ProjectsSlugMembersRoute
  '/projects/$slug/roles': typeof ProjectsSlugRolesRoute
  '/projects/$slug/settings': typeof ProjectsSlugSettingsRoute
  '/projects/$slug/surveys': typeof ProjectsSlugSurveysRoute
  '/projects/$slug': typeof ProjectsSlugIndexRoute
  '/projects/$slug/$surveySlug/builder': typeof ProjectsSlugSurveySlugBuilderRoute
  '/projects/$slug/$surveySlug/links': typeof ProjectsSlugSurveySlugLinksRoute
  '/projects/$slug/$surveySlug/members': typeof ProjectsSlugSurveySlugMembersRoute
  '/projects/$slug/$surveySlug/overview': typeof ProjectsSlugSurveySlugOverviewRoute
  '/projects/$slug/$surveySlug/responses': typeof ProjectsSlugSurveySlugResponsesRoute
  '/projects/$slug/$surveySlug/settings': typeof ProjectsSlugSurveySlugSettingsRoute
  '/projects/$slug/$surveySlug/versions': typeof ProjectsSlugSurveySlugVersionsRoute
  '/projects/$slug/$surveySlug': typeof ProjectsSlugSurveySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/ui-test/': typeof UiTestIndexRoute
  '/projects/$slug/$surveySlug': typeof ProjectsSlugSurveySlugRouteWithChildren
  '/projects/$slug/management': typeof ProjectsSlugManagementRoute
  '/projects/$slug/members': typeof ProjectsSlugMembersRoute
  '/projects/$slug/roles': typeof ProjectsSlugRolesRoute
  '/projects/$slug/settings': typeof ProjectsSlugSettingsRoute
  '/projects/$slug/surveys': typeof ProjectsSlugSurveysRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
  '/projects/$slug/$surveySlug/builder': typeof ProjectsSlugSurveySlugBuilderRoute
  '/projects/$slug/$surveySlug/links': typeof ProjectsSlugSurveySlugLinksRoute
  '/projects/$slug/$surveySlug/members': typeof ProjectsSlugSurveySlugMembersRoute
  '/projects/$slug/$surveySlug/overview': typeof ProjectsSlugSurveySlugOverviewRoute
  '/projects/$slug/$surveySlug/responses': typeof ProjectsSlugSurveySlugResponsesRoute
  '/projects/$slug/$surveySlug/settings': typeof ProjectsSlugSurveySlugSettingsRoute
  '/projects/$slug/$surveySlug/versions': typeof ProjectsSlugSurveySlugVersionsRoute
  '/projects/$slug/$surveySlug/': typeof ProjectsSlugSurveySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$slug'
    | '/projects/'
    | '/ui-test/'
    | '/projects/$slug/$surveySlug'
    | '/projects/$slug/management'
    | '/projects/$slug/members'
    | '/projects/$slug/roles'
    | '/projects/$slug/settings'
    | '/projects/$slug/surveys'
    | '/projects/$slug/'
    | '/projects/$slug/$surveySlug/builder'
    | '/projects/$slug/$surveySlug/links'
    | '/projects/$slug/$surveySlug/members'
    | '/projects/$slug/$surveySlug/overview'
    | '/projects/$slug/$surveySlug/responses'
    | '/projects/$slug/$surveySlug/settings'
    | '/projects/$slug/$surveySlug/versions'
    | '/projects/$slug/$surveySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/ui-test'
    | '/projects/$slug/management'
    | '/projects/$slug/members'
    | '/projects/$slug/roles'
    | '/projects/$slug/settings'
    | '/projects/$slug/surveys'
    | '/projects/$slug'
    | '/projects/$slug/$surveySlug/builder'
    | '/projects/$slug/$surveySlug/links'
    | '/projects/$slug/$surveySlug/members'
    | '/projects/$slug/$surveySlug/overview'
    | '/projects/$slug/$surveySlug/responses'
    | '/projects/$slug/$surveySlug/settings'
    | '/projects/$slug/$surveySlug/versions'
    | '/projects/$slug/$surveySlug'
  id:
    | '__root__'
    | '/'
    | '/projects/$slug'
    | '/projects/'
    | '/ui-test/'
    | '/projects/$slug/$surveySlug'
    | '/projects/$slug/management'
    | '/projects/$slug/members'
    | '/projects/$slug/roles'
    | '/projects/$slug/settings'
    | '/projects/$slug/surveys'
    | '/projects/$slug/'
    | '/projects/$slug/$surveySlug/builder'
    | '/projects/$slug/$surveySlug/links'
    | '/projects/$slug/$surveySlug/members'
    | '/projects/$slug/$surveySlug/overview'
    | '/projects/$slug/$surveySlug/responses'
    | '/projects/$slug/$surveySlug/settings'
    | '/projects/$slug/$surveySlug/versions'
    | '/projects/$slug/$surveySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  UiTestIndexRoute: typeof UiTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-test/': {
      id: '/ui-test/'
      path: '/ui-test'
      fullPath: '/ui-test/'
      preLoaderRoute: typeof UiTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/': {
      id: '/projects/$slug/'
      path: '/'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof ProjectsSlugIndexRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/surveys': {
      id: '/projects/$slug/surveys'
      path: '/surveys'
      fullPath: '/projects/$slug/surveys'
      preLoaderRoute: typeof ProjectsSlugSurveysRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/settings': {
      id: '/projects/$slug/settings'
      path: '/settings'
      fullPath: '/projects/$slug/settings'
      preLoaderRoute: typeof ProjectsSlugSettingsRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/roles': {
      id: '/projects/$slug/roles'
      path: '/roles'
      fullPath: '/projects/$slug/roles'
      preLoaderRoute: typeof ProjectsSlugRolesRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/members': {
      id: '/projects/$slug/members'
      path: '/members'
      fullPath: '/projects/$slug/members'
      preLoaderRoute: typeof ProjectsSlugMembersRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/management': {
      id: '/projects/$slug/management'
      path: '/management'
      fullPath: '/projects/$slug/management'
      preLoaderRoute: typeof ProjectsSlugManagementRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/$surveySlug': {
      id: '/projects/$slug/$surveySlug'
      path: '/$surveySlug'
      fullPath: '/projects/$slug/$surveySlug'
      preLoaderRoute: typeof ProjectsSlugSurveySlugRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/$surveySlug/': {
      id: '/projects/$slug/$surveySlug/'
      path: '/'
      fullPath: '/projects/$slug/$surveySlug/'
      preLoaderRoute: typeof ProjectsSlugSurveySlugIndexRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
    '/projects/$slug/$surveySlug/versions': {
      id: '/projects/$slug/$surveySlug/versions'
      path: '/versions'
      fullPath: '/projects/$slug/$surveySlug/versions'
      preLoaderRoute: typeof ProjectsSlugSurveySlugVersionsRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
    '/projects/$slug/$surveySlug/settings': {
      id: '/projects/$slug/$surveySlug/settings'
      path: '/settings'
      fullPath: '/projects/$slug/$surveySlug/settings'
      preLoaderRoute: typeof ProjectsSlugSurveySlugSettingsRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
    '/projects/$slug/$surveySlug/responses': {
      id: '/projects/$slug/$surveySlug/responses'
      path: '/responses'
      fullPath: '/projects/$slug/$surveySlug/responses'
      preLoaderRoute: typeof ProjectsSlugSurveySlugResponsesRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
    '/projects/$slug/$surveySlug/overview': {
      id: '/projects/$slug/$surveySlug/overview'
      path: '/overview'
      fullPath: '/projects/$slug/$surveySlug/overview'
      preLoaderRoute: typeof ProjectsSlugSurveySlugOverviewRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
    '/projects/$slug/$surveySlug/members': {
      id: '/projects/$slug/$surveySlug/members'
      path: '/members'
      fullPath: '/projects/$slug/$surveySlug/members'
      preLoaderRoute: typeof ProjectsSlugSurveySlugMembersRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
    '/projects/$slug/$surveySlug/links': {
      id: '/projects/$slug/$surveySlug/links'
      path: '/links'
      fullPath: '/projects/$slug/$surveySlug/links'
      preLoaderRoute: typeof ProjectsSlugSurveySlugLinksRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
    '/projects/$slug/$surveySlug/builder': {
      id: '/projects/$slug/$surveySlug/builder'
      path: '/builder'
      fullPath: '/projects/$slug/$surveySlug/builder'
      preLoaderRoute: typeof ProjectsSlugSurveySlugBuilderRouteImport
      parentRoute: typeof ProjectsSlugSurveySlugRoute
    }
  }
}

interface ProjectsSlugSurveySlugRouteChildren {
  ProjectsSlugSurveySlugBuilderRoute: typeof ProjectsSlugSurveySlugBuilderRoute
  ProjectsSlugSurveySlugLinksRoute: typeof ProjectsSlugSurveySlugLinksRoute
  ProjectsSlugSurveySlugMembersRoute: typeof ProjectsSlugSurveySlugMembersRoute
  ProjectsSlugSurveySlugOverviewRoute: typeof ProjectsSlugSurveySlugOverviewRoute
  ProjectsSlugSurveySlugResponsesRoute: typeof ProjectsSlugSurveySlugResponsesRoute
  ProjectsSlugSurveySlugSettingsRoute: typeof ProjectsSlugSurveySlugSettingsRoute
  ProjectsSlugSurveySlugVersionsRoute: typeof ProjectsSlugSurveySlugVersionsRoute
  ProjectsSlugSurveySlugIndexRoute: typeof ProjectsSlugSurveySlugIndexRoute
}

const ProjectsSlugSurveySlugRouteChildren: ProjectsSlugSurveySlugRouteChildren =
  {
    ProjectsSlugSurveySlugBuilderRoute: ProjectsSlugSurveySlugBuilderRoute,
    ProjectsSlugSurveySlugLinksRoute: ProjectsSlugSurveySlugLinksRoute,
    ProjectsSlugSurveySlugMembersRoute: ProjectsSlugSurveySlugMembersRoute,
    ProjectsSlugSurveySlugOverviewRoute: ProjectsSlugSurveySlugOverviewRoute,
    ProjectsSlugSurveySlugResponsesRoute: ProjectsSlugSurveySlugResponsesRoute,
    ProjectsSlugSurveySlugSettingsRoute: ProjectsSlugSurveySlugSettingsRoute,
    ProjectsSlugSurveySlugVersionsRoute: ProjectsSlugSurveySlugVersionsRoute,
    ProjectsSlugSurveySlugIndexRoute: ProjectsSlugSurveySlugIndexRoute,
  }

const ProjectsSlugSurveySlugRouteWithChildren =
  ProjectsSlugSurveySlugRoute._addFileChildren(
    ProjectsSlugSurveySlugRouteChildren,
  )

interface ProjectsSlugRouteChildren {
  ProjectsSlugSurveySlugRoute: typeof ProjectsSlugSurveySlugRouteWithChildren
  ProjectsSlugManagementRoute: typeof ProjectsSlugManagementRoute
  ProjectsSlugMembersRoute: typeof ProjectsSlugMembersRoute
  ProjectsSlugRolesRoute: typeof ProjectsSlugRolesRoute
  ProjectsSlugSettingsRoute: typeof ProjectsSlugSettingsRoute
  ProjectsSlugSurveysRoute: typeof ProjectsSlugSurveysRoute
  ProjectsSlugIndexRoute: typeof ProjectsSlugIndexRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugSurveySlugRoute: ProjectsSlugSurveySlugRouteWithChildren,
  ProjectsSlugManagementRoute: ProjectsSlugManagementRoute,
  ProjectsSlugMembersRoute: ProjectsSlugMembersRoute,
  ProjectsSlugRolesRoute: ProjectsSlugRolesRoute,
  ProjectsSlugSettingsRoute: ProjectsSlugSettingsRoute,
  ProjectsSlugSurveysRoute: ProjectsSlugSurveysRoute,
  ProjectsSlugIndexRoute: ProjectsSlugIndexRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  UiTestIndexRoute: UiTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
