#!/usr/bin/env python3
"""Generate a deterministic repository tree in the selected docs root."""
from __future__ import annotations

import argparse
import subprocess
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SKIP = {".git", "node_modules", ".venv", "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache", "cdk.out", "dist", ".astro", "coverage"}


def tracked_paths() -> set[Path]:
    result = subprocess.run(
        [
            "git",
            "-C",
            str(ROOT),
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "-z",
        ],
        check=True,
        capture_output=True,
    )
    return {
        path
        for value in result.stdout.split(b"\0")
        if value
        for path in [Path(value.decode())]
        if (ROOT / path).is_file()
        and path.parts[0] != "old-docs"
    }


def tree(paths: set[Path], depth: int = 4) -> list[str]:
    directories = {parent for path in paths for parent in path.parents if parent != Path(".")}
    all_paths = paths | directories
    def children(parent: Path, prefix: str, level: int) -> list[str]:
        if level > depth:
            return []
        items = sorted((p for p in all_paths if p.parent == parent and p.name not in SKIP and p.name != ".env"), key=lambda p: (p not in directories, p.name.lower()))
        result = []
        for index, item in enumerate(items):
            last = index == len(items) - 1
            result.append(prefix + ("└── " if last else "├── ") + item.name + ("/" if item in directories else ""))
            if item in directories:
                result.extend(children(item, prefix + ("    " if last else "│   "), level + 1))
        return result
    return children(Path("."), "", 1)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--docs-root", default="docs")
    parser.add_argument("--depth", type=int, default=4)
    args = parser.parse_args()
    output = ROOT / args.docs_root / "project-knowledge/reference/generated/repository-tree.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(tree(tracked_paths(), args.depth))
    output.write_text(f'''---
title: Repository tree snapshot
aliases: ["Repository tree snapshot"]
document_type: generated
status: draft
authority: canonical
verified_evidence_digest: null
last_edited: {date.today().isoformat()}
tags: [meta]
related_code: []
related_docs: ["Generated reference documentation", "Reference documentation"]
---

# Repository tree snapshot

This is reproducible generated output. Do not edit it manually.

## Generator

Generated by `tools/docs/generate-repository-tree.py`.

## Source files scanned

Git-tracked repository files and their parent directories, excluding dependency,
cache, VCS, and build-output directories.

## Regeneration

Run `python3 tools/docs/generate-repository-tree.py --docs-root {args.docs_root}` from the repository root.

## Manual editing policy

Do not edit this file manually. Change the tracked repository structure or the
generator, then regenerate it.

## Tree

```text
{ROOT.name}/
{body}
```

## Related documents

- [[generated-index|Generated reference documentation]]
- [[reference-index|Reference documentation]]
''')
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
