#!/usr/bin/env python3
"""Regenerate deterministic generated reference catalogues.

Run from the repository root. ``--docs-root`` selects the documentation tree.
Docsys owns the JSON discovery products and health dashboard.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATOR = "tools/docs/generate-reference-docs.py"


def tracked(prefix: str = "") -> list[Path]:
    result = subprocess.run(
        [
            "git",
            "-C",
            str(ROOT),
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "-z",
        ],
        check=True,
        capture_output=True,
        text=False,
    )
    paths = {
        Path(value.decode())
        for value in result.stdout.split(b"\0")
        if value
    }
    return sorted(
        path
        for path in paths
        if (ROOT / path).is_file()
        and path.parts[0] != "old-docs"
        and (not prefix or str(path).startswith(prefix))
    )


def markdown(title: str, tags: list[str], sources: list[str], body: str) -> str:
    source_lines = "\n".join(f"- `{source}`" for source in sources)
    tag_line = ", ".join(tags)
    return f"""---
title: {title}
aliases: [\"{title}\"]
document_type: generated
status: draft
authority: canonical
verified_evidence_digest: null
last_edited: {date.today().isoformat()}
tags: [{tag_line}]
related_code: []
related_docs: [\"Generated reference documentation\", \"Reference documentation\"]
---

# {title}

This is reproducible generated output. Do not edit it manually.

## Generator

Generated by `{GENERATOR}`.

## Source files scanned

{source_lines}

## Regeneration

Run `python3 {GENERATOR} --docs-root docs` from the repository root.

## Manual editing policy

Do not edit this file manually. Change the scanned source or generator, then
regenerate it.

{body}

## Related documents

- [[generated-index|Generated reference documentation]]
- [[reference-index|Reference documentation]]
"""


def api_routes() -> str:
    rows = []
    pattern = re.compile(r"@[^\n]*?\.route\(\s*[\"']([^\"']+)[\"'](?:\s*,\s*methods\s*=\s*\[([^]]+)\])?")
    for path in tracked("backend/app/api/"):
        if path.suffix != ".py":
            continue
        for route, methods in pattern.findall((ROOT / path).read_text(errors="replace")):
            rendered = methods.replace("'", "").replace('"', "").replace(" ", "") if methods else "GET"
            rows.append((route, rendered or "GET", str(path)))
    table = "\n".join(f"| `{route}` | `{methods}` | `{source}` |" for route, methods, source in sorted(set(rows))) or "_No Flask route decorators found._"
    return markdown("API routes", ["backend"], ["backend/app/api/v1/**/*.py"],
                    "## Routes\n\n| Route | Methods | Source |\n| --- | --- | --- |\n" + table)


def workflows() -> str:
    rows = []
    for path in tracked(".github/workflows/"):
        text = (ROOT / path).read_text(errors="replace")
        name = next((line.split(":", 1)[1].strip().strip("'\"") for line in text.splitlines() if line.startswith("name:")), path.stem)
        triggers = next((line.strip() for line in text.splitlines() if line.startswith("on:")), "on: (mapping)")
        rows.append(f"| `{path.name}` | {name} | `{triggers}` |")
    return markdown("CI workflows", ["ci-cd"], [".github/workflows/*.yml", ".github/workflows/*.yaml"],
                    "## Workflow inventory\n\n| File | Name | Trigger declaration |\n| --- | --- | --- |\n" + "\n".join(sorted(rows)))


def configuration() -> str:
    names: set[str] = set()
    for path in tracked():
        if path.suffix not in {".py", ".sh", ".yml", ".yaml", ".json", ".md"}:
            continue
        if not str(path).startswith(("backend/", "infra/", "scripts/", ".github/")):
            continue
        names.update(re.findall(r"\b(?:FLOWFORM|AUTH0|AWS|DATABASE|POSTGRES|GRAFANA)_[A-Z0-9_]+\b", (ROOT / path).read_text(errors="replace")))
    rows = "\n".join(f"| `{name}` | repository configuration reference |" for name in sorted(names))
    return markdown("Configuration index", ["configuration"], ["backend/", "infra/", "scripts/", ".github/"],
                    "## Names discovered\n\n| Name | Discovery scope |\n| --- | --- |\n" + rows)


def dependencies() -> str:
    rows = []
    for path in tracked():
        if path.name == "pyproject.toml":
            rows.append(f"| Python project | `{path}` | `project dependencies and tool configuration` |")
        elif path.name == "package.json" and str(path).startswith("frontend/"):
            data = json.loads((ROOT / path).read_text())
            deps = sorted(set((data.get("dependencies") or {}) | (data.get("devDependencies") or {})))
            rows.append(f"| {data.get('name', path.parent.name)} | `{path}` | {', '.join(f'`{d}`' for d in deps) or '_none_'} |")
    return markdown("Dependency map", ["tooling"], ["**/pyproject.toml", "frontend/**/package.json"],
                    "## Manifest inventory\n\n| Component | Manifest | Declared packages |\n| --- | --- | --- |\n" + "\n".join(sorted(rows)))


def infrastructure() -> str:
    paths = [str(p) for p in tracked("infra/") if p.suffix in {".py", ".tf", ".yml", ".yaml", ".sh", ".json"}]
    rows = "\n".join(f"- `{path}`" for path in paths)
    return markdown("Infrastructure resources", ["infrastructure"], ["infra/**/*.py", "infra/**/*.tf", "infra/**/*.yml", "infra/**/*.yaml", "infra/**/*.sh"],
                    "## Declared infrastructure source inventory\n\n" + (rows or "_No matching tracked sources._"))


def generated_index() -> str:
    content = markdown("Generated reference documentation", ["meta"], [GENERATOR, "tools/docs/generate-repository-tree.py", "tools/docs/docsys/"],
                    "## Contents\n\nThis branch contains reproducible inventories and Docsys discovery snapshots. It does not own explanatory architecture.\n\n- [[api-routes|API routes]]\n- [[ci-workflows|CI workflows]]\n- [[configuration-index|Configuration index]]\n- [[dependency-map|Dependency map]]\n- [[infrastructure-resources|Infrastructure resources]]\n- [[repository-tree|Repository tree snapshot]]\n- [[documentation-dashboard|Documentation health dashboard]]")
    return content.replace('related_docs: ["Generated reference documentation", "Reference documentation"]',
                           'related_docs: ["Reference documentation"]')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--docs-root", default="docs")
    args = parser.parse_args()
    out = ROOT / args.docs_root / "project-knowledge/reference/generated"
    out.mkdir(parents=True, exist_ok=True)
    products = {
        "generated-index.md": generated_index(), "api-routes.md": api_routes(),
        "ci-workflows.md": workflows(), "configuration-index.md": configuration(),
        "dependency-map.md": dependencies(), "infrastructure-resources.md": infrastructure(),
    }
    for name, content in products.items():
        (out / name).write_text(content)
        print(f"wrote {out / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
