#!/usr/bin/env python3
"""Generate the repository tree snapshot for docs/90-generated/.

Creates a reproducible, dependency-free tree of the repository in
docs/90-generated/repository-tree.md, with front matter conforming to the
knowledge-network conventions in docs/00-overview/documentation-model.md.
Dependency, cache, VCS, and build-output directories are skipped.
"""
from pathlib import Path

SKIP = {".git", "node_modules", ".venv", "__pycache__", ".mypy_cache",
        ".pytest_cache", ".ruff_cache", "cdk.out", "dist", ".astro", "coverage"}
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs/90-generated/repository-tree.md"


def walk(path, prefix="", depth=0, max_depth=4):
    if depth > max_depth:
        return []
    rows = []
    entries = sorted([p for p in path.iterdir() if p.name not in SKIP],
                     key=lambda p: (p.is_file(), p.name.lower()))
    for i, p in enumerate(entries):
        branch = "└── " if i == len(entries) - 1 else "├── "
        rows.append(prefix + branch + p.name + ("/" if p.is_dir() else ""))
        if p.is_dir():
            rows.extend(walk(p, prefix + ("    " if i == len(entries) - 1 else "│   "),
                             depth + 1, max_depth))
    return rows


body = """---
title: Repository tree snapshot
document_type: generated
status: scaffold
authority: canonical
verified_against_commit: null
related_code: []
related_docs:
  - "Generated documentation"
  - "Repository tree"
---

# Repository tree snapshot

Generated repository tree snapshot. Do not edit manually; regenerate instead.

## Generator

This file is generated by `scripts/docs/generate-repository-tree.py`.

## Source files scanned

The generator walks repository directories to a depth of four levels, skipping
dependency, cache, VCS, and build-output folders: """ + ", ".join(
    f"`{s}`" for s in sorted(SKIP)) + """.

## Tree

```text
""" + ROOT.name + "/\n" + "\n".join(walk(ROOT)) + """
```

## Regeneration procedure

Run `python3 scripts/docs/generate-repository-tree.py` from the repository root.

## Related documents

- [[Generated documentation]]
- [[Repository tree]]
"""
OUT.write_text(body)
print(f"wrote {OUT}")
