#!/usr/bin/env python3
"""Generate a basic repository tree for documentation.

Metadata:
- title: Generate repository tree
- document_type: docs-script
- status: scaffold
- authority: canonical
- verified_against_commit: null

Purpose:
Creates a reproducible, dependency-free tree snapshot for docs/90-generated/repository-tree.md.
Sections: configuration, traversal, rendering, output, TODO verification.
TODO: Verify this against the current implementation.
"""
from pathlib import Path
SKIP={'.git','node_modules','.venv','__pycache__'}
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'docs/90-generated/repository-tree.md'
def walk(path, prefix='', depth=0, max_depth=4):
    if depth>max_depth: return []
    rows=[]
    entries=sorted([p for p in path.iterdir() if p.name not in SKIP], key=lambda p:(p.is_file(), p.name.lower()))
    for i,p in enumerate(entries):
        branch='└── ' if i==len(entries)-1 else '├── '
        rows.append(prefix+branch+p.name+('/' if p.is_dir() else ''))
        if p.is_dir(): rows.extend(walk(p, prefix+('    ' if i==len(entries)-1 else '│   '), depth+1, max_depth))
    return rows
body='''---
title: Repository Tree
document_type: generated
status: scaffold
authority: canonical
verified_against_commit: null
related_code: []
related_docs: ["../00-overview/documentation-generator-guide.md"]
---

# Repository Tree
Generated repository tree snapshot.

## Generated status
This file is generated by `scripts/docs/generate-repository-tree.py`. Do not manually edit generated content below.
TODO: Verify this against the current implementation.

## Source files scanned
The generator scans repository directories while skipping common dependency and VCS folders.
TODO: Verify this against the current implementation.

## Tree
```text
'''+ROOT.name+'/\n'+'\n'.join(walk(ROOT))+'''\n```

## Regeneration procedure
Run `python scripts/docs/generate-repository-tree.py` from the repository root.
TODO: Verify this against the current implementation.
'''
OUT.write_text(body)
print(f'wrote {OUT}')
