#!/usr/bin/env python3
"""CI documentation-review step.

Runs the documentation impact detector for a pull request and produces a report
that assists reviewers. It:

- computes documentation impacted by the code changes in the range
- indicates whether each impacted document was modified in the same change
- writes a Markdown summary (for a PR comment / job summary) and JSON
- exits non-zero only when a *critical* documentation area is impacted but
  left unmodified, and only if the repository configures critical globs
  (``critical_doc_globs`` in ``scripts/docs/docsys.config.json``)

By default nothing fails CI: the goal is to surface documentation that may need
review, not to force meaningless documentation edits. Usage:

    python3 -m docsys.ci --base origin/main --head HEAD \
        --markdown docs-impact.md --json docs-impact.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .config import Config
from .impact import impact_report
from .model import DocSet, pattern_matches

_ICON = {"high": "🔴", "medium": "🟠", "low": "🟡"}


def render_markdown(report: dict, critical_paths: list[str]) -> str:
    impacted = report["impacted_documents"]
    if not impacted:
        return (
            "## 📄 Documentation impact\n\n"
            f"No documented areas are affected by this change "
            f"(`{report['comparison']}`).\n"
        )

    unedited = [d for d in impacted if not d["modified_in_change"]]
    edited = [d for d in impacted if d["modified_in_change"]]

    lines = [
        "## 📄 Documentation impact",
        "",
        f"This change touches code owned by **{len(impacted)}** documented "
        f"area(s) (`{report['comparison']}`). Review whether the documentation "
        "below still matches the implementation — this check does not require "
        "edits.",
        "",
    ]
    if critical_paths:
        lines.append(
            f"> ⚠️ **{len(critical_paths)} critical document(s) impacted but not "
            "updated** — see the checklist below."
        )
        lines.append("")

    lines.append("### Impacted documents needing a look")
    lines.append("")
    if unedited:
        lines.append("| Confidence | Document | Why |")
        lines.append("| --- | --- | --- |")
        for d in unedited:
            reason = d["reasons"][0] if d["reasons"] else ""
            icon = _ICON.get(d["confidence"], "")
            crit = " **(critical)**" if d["path"] in critical_paths else ""
            lines.append(
                f"| {icon} {d['confidence']} | `{d['path']}`{crit} | {reason} |"
            )
    else:
        lines.append("_All impacted documents were updated in this change._")
    lines.append("")

    if edited:
        lines.append("### Already updated in this PR")
        lines.append("")
        for d in edited:
            lines.append(f"- ✅ `{d['path']}`")
        lines.append("")

    lines.append(
        "<sub>Generated by `scripts/docs/docsys/ci.py`. Confidence reflects how "
        "directly the changed code maps to each document's `related_code`.</sub>"
    )
    return "\n".join(lines) + "\n"


def run(
    base: str | None,
    head: str | None,
    markdown_path: Path | None,
    json_path: Path | None,
    fail_on_critical: bool,
) -> int:
    config = Config.load()
    docset = DocSet.load()
    report = impact_report(base, head, docset)

    # Which impacted-but-unmodified documents fall under a critical glob?
    critical_paths = []
    if config.critical_doc_globs:
        for d in report["impacted_documents"]:
            if d["modified_in_change"]:
                continue
            if any(
                pattern_matches(g if g.endswith("/") else g, d["path"])
                or _glob_hit(g, d["path"])
                for g in config.critical_doc_globs
            ):
                critical_paths.append(d["path"])

    md = render_markdown(report, critical_paths)
    if markdown_path:
        markdown_path.write_text(md)
    else:
        print(md)
    if json_path:
        report["critical_impacted"] = critical_paths
        json_path.write_text(json.dumps(report, indent=2) + "\n")

    if fail_on_critical and critical_paths:
        print(
            f"::error::{len(critical_paths)} critical document(s) impacted but "
            "not updated: " + ", ".join(critical_paths)
        )
        return 1
    return 0


def _glob_hit(glob: str, path: str) -> bool:
    import fnmatch

    return fnmatch.fnmatch(path, glob)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="docsys.ci")
    parser.add_argument("--base", help="base ref (e.g. origin/main)")
    parser.add_argument("--head", default="HEAD", help="head ref")
    parser.add_argument("--markdown", type=Path, help="write Markdown summary here")
    parser.add_argument("--json", type=Path, help="write JSON report here")
    parser.add_argument(
        "--fail-on-critical",
        action="store_true",
        help="exit non-zero if a critical doc is impacted but unmodified",
    )
    args = parser.parse_args(argv)
    return run(args.base, args.head, args.markdown, args.json, args.fail_on_critical)


if __name__ == "__main__":
    raise SystemExit(main())
