\set ON_ERROR_STOP on

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${FLOWFORM_CORE_APP_USER}') THEN
        CREATE ROLE ${FLOWFORM_CORE_APP_USER} LOGIN PASSWORD '${FLOWFORM_CORE_APP_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${FLOWFORM_RESPONSE_APP_USER}') THEN
        CREATE ROLE ${FLOWFORM_RESPONSE_APP_USER} LOGIN PASSWORD '${FLOWFORM_RESPONSE_APP_PASSWORD}';
    END IF;
END
$$;

GRANT CONNECT ON DATABASE ${FLOWFORM_CORE_DB} TO ${FLOWFORM_CORE_APP_USER};
GRANT CONNECT ON DATABASE ${FLOWFORM_RESPONSE_DB} TO ${FLOWFORM_RESPONSE_APP_USER};