\set ON_ERROR_STOP on

\connect ${FLOWFORM_CORE_DB}

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO ${FLOWFORM_CORE_APP_USER};

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO ${FLOWFORM_CORE_APP_USER};

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO ${FLOWFORM_CORE_APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${FLOWFORM_CORE_APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${FLOWFORM_CORE_APP_USER};

\connect ${FLOWFORM_RESPONSE_DB}

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO ${FLOWFORM_RESPONSE_APP_USER};

GRANT SELECT, INSERT, UPDATE
ON ALL TABLES IN SCHEMA public
TO ${FLOWFORM_RESPONSE_APP_USER};

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO ${FLOWFORM_RESPONSE_APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE ON TABLES TO ${FLOWFORM_RESPONSE_APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${FLOWFORM_RESPONSE_APP_USER};