#!/usr/bin/env bash
set -Eeuo pipefail

# Proxmox host prerequisites for the FlowForm rehearsal (run ON the PVE host).
#
#   A. Create private bridge vmbr10 (no ports, no gateway) via a dedicated
#      file in /etc/network/interfaces.d/ — the PVE-safe way that does not
#      touch the autogenerated /etc/network/interfaces.
#   B. Enable "snippets" content on the "local" storage so VMs can be handed
#      custom cloud-init user-data via `qm set --cicustom`.
#
# Idempotent: re-running is a no-op if both are already in place.
# Reversible: `--undo` removes vmbr10 and reverts the storage content list.
#
# Does NOT touch vmbr0, the physical NICs, or any existing VM.

BRIDGE_FILE="/etc/network/interfaces.d/vmbr10"
STORAGE="local"
BASE_CONTENT="iso,import,vztmpl,backup"

undo() {
  echo "== undo =="
  if [[ -f "${BRIDGE_FILE}" ]]; then
    rm -f "${BRIDGE_FILE}"
    ifreload -a
    echo "removed ${BRIDGE_FILE} and reloaded network"
  else
    echo "${BRIDGE_FILE} already absent"
  fi
  pvesm set "${STORAGE}" --content "${BASE_CONTENT}"
  echo "reset ${STORAGE} content to ${BASE_CONTENT}"
  exit 0
}

[[ "${1:-}" == "--undo" ]] && undo

# --- A. vmbr10 ---
desired_bridge="$(mktemp)"
trap 'rm -f "${desired_bridge}"' EXIT
cat > "${desired_bridge}" <<'EOF'
auto vmbr10
iface vmbr10 inet static
	address 10.10.10.1/24
	bridge-ports none
	bridge-stp off
	bridge-fd 0
	# Private FlowForm rehearsal net. No bridge-ports = not wired to any
	# physical NIC; the host address exists only for orchestration and health
	# checks. No gateway is advertised to the private VMs, so a VM whose only NIC is
	# vmbr10 structurally has no default route off the bridge.
EOF
if [[ ! -f "${BRIDGE_FILE}" ]] || ! cmp -s "${desired_bridge}" "${BRIDGE_FILE}"; then
  echo "A: installing ${BRIDGE_FILE}"
  install -m 0644 "${desired_bridge}" "${BRIDGE_FILE}"
  ifreload -a
else
  echo "A: ${BRIDGE_FILE} already matches — skipping"
fi
ip -br addr show vmbr10

# --- B. snippets on local ---
echo "B: enabling snippets on '${STORAGE}'"
pvesm set "${STORAGE}" --content "${BASE_CONTENT},snippets"
pvesm status --content snippets

echo "== done =="
