\set ON_ERROR_STOP on \connect ${FF_PGDB_RESPONSE__DB_NAME}

GRANT USAGE ON SCHEMA response_app TO ${FF_PGDB_RESPONSE__APP_USER};

GRANT SELECT, INSERT, UPDATE
ON ALL TABLES IN SCHEMA response_app
TO ${FF_PGDB_RESPONSE__APP_USER};

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA response_app
TO ${FF_PGDB_RESPONSE__APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE flowform_owner IN SCHEMA response_app
GRANT SELECT, INSERT, UPDATE ON TABLES
TO ${FF_PGDB_RESPONSE__APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE flowform_owner IN SCHEMA response_app
GRANT USAGE, SELECT, UPDATE ON SEQUENCES
TO ${FF_PGDB_RESPONSE__APP_USER};

ALTER ROLE ${FF_PGDB_RESPONSE__APP_USER} SET search_path = response_app;