\set ON_ERROR_STOP on \connect ${DATABASE_RESPONSE_NAME}

GRANT USAGE ON SCHEMA response_app TO ${DATABASE_RESPONSE_APP_USER};

GRANT SELECT, INSERT, UPDATE
ON ALL TABLES IN SCHEMA response_app
TO ${DATABASE_RESPONSE_APP_USER};

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA response_app
TO ${DATABASE_RESPONSE_APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE flowform_owner IN SCHEMA response_app
GRANT SELECT, INSERT, UPDATE ON TABLES
TO ${DATABASE_RESPONSE_APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE flowform_owner IN SCHEMA response_app
GRANT USAGE, SELECT, UPDATE ON SEQUENCES
TO ${DATABASE_RESPONSE_APP_USER};

ALTER ROLE ${DATABASE_RESPONSE_APP_USER} SET search_path = response_app;
