#!/usr/bin/env python3
"""Regenerate the small set of useful generated reference catalogues.

Run from the repository root. ``--docs-root`` selects the documentation tree.
Docsys owns the JSON discovery products and health dashboard.
"""
from __future__ import annotations

import argparse
import re
import subprocess
from datetime import date
from pathlib import Path

from flowform_tools.paths import ROOT

GENERATOR = "tools/bin/docsys generate-reference"


def tracked(prefix: str = "") -> list[Path]:
    result = subprocess.run(
        [
            "git",
            "-C",
            str(ROOT),
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "-z",
        ],
        check=True,
        capture_output=True,
        text=False,
    )
    paths = {
        Path(value.decode())
        for value in result.stdout.split(b"\0")
        if value
    }
    return sorted(
        path
        for path in paths
        if (ROOT / path).is_file()
        and not path.is_relative_to(Path("docs/development-workspace/archive/old-docs"))
        and (not prefix or str(path).startswith(prefix))
    )


def markdown(title: str, tags: list[str], sources: list[str], body: str) -> str:
    source_lines = "\n".join(f"- `{source}`" for source in sources)
    tag_line = ", ".join(tags)
    return f"""---
title: {title}
aliases: [\"{title}\"]
document_type: generated
status: draft
authority: canonical
verified_evidence_digest: null
last_edited: {date.today().isoformat()}
tags: [{tag_line}]
related_code: []
related_docs: [\"Generated reference documentation\", \"Reference documentation\"]
---

# {title}

This is reproducible generated output. Do not edit it manually.

## Generator

Generated by `{GENERATOR}`.

## Source files scanned

{source_lines}

## Regeneration

Run `python3 {GENERATOR} --docs-root docs` from the repository root.

## Manual editing policy

Do not edit this file manually. Change the scanned source or generator, then
regenerate it.

{body}

## Related documents

- [[generated-index|Generated reference documentation]]
- [[reference-index|Reference documentation]]
"""


def api_routes() -> str:
    rows = []
    pattern = re.compile(r"@[^\n]*?\.route\(\s*[\"']([^\"']+)[\"'](?:\s*,\s*methods\s*=\s*\[([^]]+)\])?")
    for path in tracked("backend/app/api/"):
        if path.suffix != ".py":
            continue
        for route, methods in pattern.findall((ROOT / path).read_text(errors="replace")):
            rendered = methods.replace("'", "").replace('"', "").replace(" ", "") if methods else "GET"
            rows.append((route, rendered or "GET", str(path)))
    table = "\n".join(f"| `{route}` | `{methods}` | `{source}` |" for route, methods, source in sorted(set(rows))) or "_No Flask route decorators found._"
    return markdown("API routes", ["backend"], ["backend/app/api/v1/**/*.py"],
                    "## Routes\n\n| Route | Methods | Source |\n| --- | --- | --- |\n" + table)


def workflows() -> str:
    rows = []
    for path in tracked(".github/workflows/"):
        text = (ROOT / path).read_text(errors="replace")
        name = next((line.split(":", 1)[1].strip().strip("'\"") for line in text.splitlines() if line.startswith("name:")), path.stem)
        triggers = next((line.strip() for line in text.splitlines() if line.startswith("on:")), "on: (mapping)")
        rows.append(f"| `{path.name}` | {name} | `{triggers}` |")
    return markdown("CI workflows", ["ci-cd"], [".github/workflows/*.yml", ".github/workflows/*.yaml"],
                    "## Workflow inventory\n\n| File | Name | Trigger declaration |\n| --- | --- | --- |\n" + "\n".join(sorted(rows)))


def generated_index() -> str:
    content = markdown("Generated reference documentation", ["meta"], [GENERATOR, "tools/flowform_tools/docsys/"],
                    "## Contents\n\nThis branch retains only compact, reproducible snapshots that are useful for navigation. It does not own explanatory architecture or exhaustive repository inventories.\n\n- [[api-routes|API routes]]\n- [[ci-workflows|CI workflows]]\n- [[documentation-dashboard|Documentation health dashboard]]")
    return (
        content.replace(
            'related_docs: ["Generated reference documentation", "Reference documentation"]',
            'related_docs: ["Reference documentation"]',
        )
        .replace(
            "- [[generated-index|Generated reference documentation]]\n",
            "",
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--docs-root", default="docs")
    args = parser.parse_args(argv)
    out = ROOT / args.docs_root / "project-knowledge/reference/generated"
    out.mkdir(parents=True, exist_ok=True)
    products = {
        "generated-index.md": generated_index(), "api-routes.md": api_routes(),
        "ci-workflows.md": workflows(),
    }
    for name, content in products.items():
        (out / name).write_text(content)
        print(f"wrote {out / name}")
    for name in (
        "configuration-index.md",
        "dependency-map.md",
        "infrastructure-resources.md",
        "repository-tree.md",
    ):
        stale = out / name
        if stale.exists():
            stale.unlink()
            print(f"removed {stale}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
