-- =========================================
-- FLOWFORM CORE DATABASE SCHEMA (TIGHTENED)
-- =========================================
-- Purpose:
-- - stores application, RBAC, survey definition, publishing, and submission registry data
-- - does NOT store raw survey answers
--
-- Design notes:
-- - hard delete is used for normal entities such as projects, surveys, stores, roles, memberships, and links
-- - only survey_versions use soft delete because old compiled versions may be required to interpret stored responses
-- - extra composite foreign keys are used to prevent cross-project and cross-survey mismatches
-- - published survey structure is defined by survey_versions.compiled_schema
-- - survey_questions / survey_rules / survey_scoring_rules are draft/build inputs and are locked once a version is published

-- =========================================
-- HELPERS
-- =========================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;


CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION prevent_changes_to_published_version_parts()
RETURNS TRIGGER AS $$
DECLARE
    v_survey_version_id BIGINT;
BEGIN
    v_survey_version_id := COALESCE(NEW.survey_version_id, OLD.survey_version_id);

    IF EXISTS (
        SELECT 1
        FROM survey_versions sv
        WHERE sv.id = v_survey_version_id
          AND sv.status = 'published'
          AND sv.deleted_at IS NULL
    ) THEN
        RAISE EXCEPTION 'Cannot modify components of a published survey version';
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_survey_published_version()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.published_version_id IS NULL THEN
        RETURN NEW;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM survey_versions sv
        WHERE sv.id = NEW.published_version_id
          AND sv.survey_id = NEW.id
          AND sv.status = 'published'
          AND sv.deleted_at IS NULL
    ) THEN
        RAISE EXCEPTION 'published_version_id must reference a published, non-deleted version of the same survey';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION protect_active_published_version()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM surveys s
        WHERE s.published_version_id = OLD.id
    ) THEN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'Cannot delete the active published survey version while it is referenced by surveys.published_version_id';
        END IF;

        IF NEW.status <> 'published' OR NEW.deleted_at IS NOT NULL THEN
            RAISE EXCEPTION 'Cannot unpublish or soft delete the active published survey version while it is referenced by surveys.published_version_id';
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION jsonb_has_exact_keys(doc jsonb, expected_keys text[])
RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT
        jsonb_typeof(doc) = 'object'
        AND doc ?& expected_keys
        AND (
            SELECT count(*)
            FROM jsonb_object_keys(doc)
        ) = (
            SELECT count(DISTINCT k)
            FROM unnest(expected_keys) AS t(k)
        );
$$;
-- =========================================
-- USERS
-- =========================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth0_user_id TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    platform_admin BOOLEAN NOT NULL DEFAULT FALSE,
    public_id TEXT NOT NULL DEFAULT (translate(encode(gen_random_bytes(6), 'base64'), '+/', '-_')) UNIQUE,

    CONSTRAINT ck_users_platform_admin CHECK (NOT platform_admin OR id = 1),
    CONSTRAINT ck_users_public_id_format CHECK (public_id ~ '^[A-Za-z0-9_-]{8}$')
);

-- =========================================
-- PROJECTS
-- =========================================

CREATE TABLE projects (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================
-- PERMISSIONS
-- =========================================

CREATE TABLE permissions (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- =========================================
-- PROJECT ROLES
-- =========================================

CREATE TABLE project_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    is_system_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_project_roles_project_id_id
        UNIQUE (project_id, id),
    CONSTRAINT uq_project_roles_project_name
        UNIQUE (project_id, name),
    CONSTRAINT ck_project_roles_description_len
        CHECK (description IS NULL OR char_length(btrim(description)) BETWEEN 1 AND 500)
);

CREATE TABLE project_role_permissions (
    role_id BIGINT NOT NULL REFERENCES project_roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- =========================================
-- PROJECT MEMBERSHIPS
-- =========================================
CREATE TABLE project_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES project_roles (id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_project_memberships_status_valid CHECK (
        status IN ('active', 'suspended')
    ),
    CONSTRAINT uq_project_memberships_user_project UNIQUE (user_id, project_id),
    CONSTRAINT uq_project_memberships_project_id_id UNIQUE (project_id, id),
    CONSTRAINT fk_project_memberships_role_same_project FOREIGN KEY (project_id, role_id) REFERENCES project_roles (project_id, id)
);

-- =========================================
-- PROJECT INVITATIONS
-- =========================================

CREATE TABLE project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    invited_email TEXT NOT NULL,
    role_id BIGINT REFERENCES project_roles (id) ON DELETE SET NULL,
    invited_by_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    invite_message TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMPTZ,
    accepted_by_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    accepted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_project_invitations_status_valid
        CHECK (status IN ('pending', 'accepted', 'declined', 'revoked')),

    -- partial unique: only one pending invite per email per project
    -- (accepted/declined/revoked rows are kept for history and don't block re-invite)

    CONSTRAINT fk_project_invitations_role_same_project
        FOREIGN KEY (project_id, role_id)
        REFERENCES project_roles (project_id, id),

    CONSTRAINT ck_project_invitations_email_len
        CHECK (char_length(btrim(invited_email)) BETWEEN 1 AND 254),

    CONSTRAINT ck_project_invitations_message_len
        CHECK (invite_message IS NULL OR char_length(btrim(invite_message)) BETWEEN 1 AND 500),

    CONSTRAINT ck_project_invitations_accepted_fields
        CHECK (
            status <> 'accepted'
            OR (accepted_by_user_id IS NOT NULL AND accepted_at IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_project_invitations_pending_project_email
    ON project_invitations (project_id, invited_email)
    WHERE status = 'pending';

CREATE INDEX idx_project_invitations_project ON project_invitations(project_id);
CREATE INDEX idx_project_invitations_email ON project_invitations(invited_email);
CREATE INDEX idx_project_invitations_status ON project_invitations(status);

-- =========================================
-- RESPONSE STORES
-- =========================================
-- Defines where a project's or survey's responses should be written.
-- For customer-managed databases, store only a reference to a secret, not raw credentials.

CREATE TABLE response_stores (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    store_type TEXT NOT NULL,
    connection_reference JSONB NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_response_stores_store_type_valid
        CHECK (store_type IN ('platform_postgres', 'external_postgres')),

    CONSTRAINT ck_response_stores_connection_reference_is_object
        CHECK (jsonb_typeof(connection_reference) = 'object'),

    CONSTRAINT uq_response_stores_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT uq_response_stores_project_id_name
        UNIQUE (project_id, name)
);

-- =========================================
-- SURVEYS
-- =========================================

CREATE TABLE surveys (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'private',
    public_slug TEXT UNIQUE,
    default_response_store_id BIGINT,
    published_version_id BIGINT,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_surveys_visibility_valid
        CHECK (visibility IN ('private', 'link_only', 'public')),

    CONSTRAINT ck_surveys_public_requires_slug
        CHECK (
            visibility <> 'public'
            OR public_slug IS NOT NULL
        ),

    CONSTRAINT ck_surveys_slug_requires_public_visibility
        CHECK (
            public_slug IS NULL
            OR visibility = 'public'
        ),

    CONSTRAINT uq_surveys_project_id_id
        UNIQUE (project_id, id),
    CONSTRAINT fk_surveys_default_store
        FOREIGN KEY (default_response_store_id)
        REFERENCES response_stores(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_surveys_default_store_same_project
        FOREIGN KEY (project_id, default_response_store_id)
        REFERENCES response_stores(project_id, id)
);

-- =========================================
-- SURVEY VERSIONS
-- =========================================
-- compiled_schema is the authoritative published artifact.
-- Only this table uses soft delete because old compiled versions may be needed later.

CREATE TABLE survey_versions (
    id BIGSERIAL PRIMARY KEY,
    survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    compiled_schema JSONB,
    published_at TIMESTAMPTZ,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_survey_versions_status_valid
        CHECK (status IN ('draft', 'published', 'archived')),

    CONSTRAINT ck_survey_versions_version_number_positive
        CHECK (version_number > 0),

    CONSTRAINT ck_survey_versions_published_requires_schema_and_timestamp
        CHECK (
            status <> 'published'
            OR (compiled_schema IS NOT NULL AND published_at IS NOT NULL)
        ),

    CONSTRAINT uq_survey_versions_survey_id_id
        UNIQUE (survey_id, id),

    CONSTRAINT uq_survey_versions_survey_id_version_number
        UNIQUE (survey_id, version_number)
);

ALTER TABLE surveys
ADD CONSTRAINT fk_surveys_published_version_same_survey
    FOREIGN KEY (id, published_version_id)
    REFERENCES survey_versions(survey_id, id)
    ON DELETE SET NULL;

CREATE UNIQUE INDEX uq_survey_versions_one_published
    ON survey_versions (survey_id)
    WHERE status = 'published' AND deleted_at IS NULL;

-- =========================================
-- SURVEY QUESTIONS
-- =========================================

CREATE TABLE survey_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    survey_version_id BIGINT NOT NULL
        REFERENCES survey_versions(id)
        ON DELETE CASCADE,

    question_key TEXT NOT NULL,
    sort_key INTEGER NOT NULL,
    node_type TEXT NOT NULL,
    question_schema JSONB NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_survey_questions_node_type_valid
        CHECK (node_type IN ('question', 'rule')),

    CONSTRAINT ck_survey_questions_sort_key_positive
        CHECK (sort_key > 0),

    CONSTRAINT ck_survey_questions_question_key_len
        CHECK (length(question_key) BETWEEN 1 AND 128),

    CONSTRAINT ck_survey_questions_question_key_format
        CHECK (question_key ~ '^[A-Za-z0-9_-]+$'),

    CONSTRAINT ck_survey_questions_schema_size
        CHECK (length(question_schema::text) <= 10000),

    CONSTRAINT ck_survey_questions_question_schema_is_object
        CHECK (
            node_type <> 'question'
            OR jsonb_typeof(question_schema) = 'object'
        ),

    CONSTRAINT ck_survey_questions_question_family_valid
        CHECK (
            node_type <> 'question'
            OR question_schema->>'family' IN ('choice', 'field', 'matching', 'rating')
        ),

    CONSTRAINT uq_survey_questions_survey_version_id_id
        UNIQUE (survey_version_id, id)
);

CREATE UNIQUE INDEX uq_survey_questions_survey_version_id_question_key
    ON survey_questions (survey_version_id, question_key);

CREATE UNIQUE INDEX uq_survey_questions_survey_version_id_sort_key
    ON survey_questions (survey_version_id, sort_key);

CREATE INDEX ix_survey_questions_survey_version_id_node_type
    ON survey_questions (survey_version_id, node_type);

CREATE INDEX ix_survey_questions_survey_version_id_sort_key
    ON survey_questions (survey_version_id, sort_key);

-- =========================================
-- SURVEY RULES
-- =========================================


-- =========================================
-- SURVEY SCORING RULES
-- =========================================

CREATE TABLE survey_scoring_rules (
    id BIGSERIAL PRIMARY KEY,
    survey_version_id BIGINT NOT NULL REFERENCES survey_versions(id) ON DELETE CASCADE,
    scoring_key TEXT NOT NULL,
    scoring_schema JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_survey_scoring_rules_survey_version_id_scoring_key
        UNIQUE (survey_version_id, scoring_key),

    CONSTRAINT ck_survey_scoring_rules_scoring_schema_is_object
        CHECK (jsonb_typeof(scoring_schema) = 'object'),

    CONSTRAINT ck_survey_scoring_rules_scoring_schema_required_keys_present
        CHECK (scoring_schema ?& ARRAY['target', 'bucket', 'strategy', 'config']),

    CONSTRAINT ck_survey_scoring_rules_scoring_target_valid
        CHECK (
            jsonb_typeof(scoring_schema->'target') = 'string'
            AND btrim(scoring_schema->>'target') <> ''
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_bucket_valid
        CHECK (
            jsonb_typeof(scoring_schema->'bucket') = 'string'
            AND btrim(scoring_schema->>'bucket') <> ''
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_strategy_valid
        CHECK (
            scoring_schema->>'strategy' IN (
                'choice_option_map',
                'matching_answer_key',
                'rating_direct',
                'field_numeric_ranges'
            )
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_config_is_object
        CHECK (
            jsonb_typeof(scoring_schema->'config') = 'object'
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_condition_is_object
        CHECK (
            (scoring_schema ? 'condition') = FALSE
            OR jsonb_typeof(scoring_schema->'condition') = 'object'
        )
);

-- =========================================
-- SURVEY ROLES (OVERRIDE MODEL)
-- =========================================

CREATE TABLE survey_roles (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_survey_roles_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT uq_survey_roles_project_id_name
        UNIQUE (project_id, name),

    CONSTRAINT ck_survey_roles_description_len
        CHECK (description IS NULL OR char_length(btrim(description)) BETWEEN 1 AND 500)
);

CREATE TABLE survey_role_permissions (
    role_id BIGINT NOT NULL REFERENCES survey_roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE survey_membership_roles (
    project_id BIGINT NOT NULL,
    survey_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (survey_id, membership_id),
    CONSTRAINT fk_survey_membership_roles_survey_same_project
        FOREIGN KEY (project_id, survey_id)
        REFERENCES surveys(project_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_survey_membership_roles_membership_same_project
        FOREIGN KEY (project_id, membership_id)
        REFERENCES project_memberships(project_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_survey_membership_roles_role_same_project
        FOREIGN KEY (project_id, role_id)
        REFERENCES survey_roles(project_id, id)
        ON DELETE CASCADE
);

-- =========================================
-- PUBLIC LINKS
-- =========================================
-- Store only a hash of the bearer token. The application should look up by
-- a short prefix, then compare the full hash.

CREATE TABLE survey_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    token_prefix TEXT NOT NULL,
    token_hash TEXT NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_auth BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_email TEXT,
    expires_at TIMESTAMPTZ,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_survey_links_token_hash
        UNIQUE (token_hash),

    CONSTRAINT uq_survey_links_survey_id_id
        UNIQUE (survey_id, id),

    CONSTRAINT uq_survey_links_survey_id_token_prefix
        UNIQUE (survey_id, token_prefix),

    CONSTRAINT ck_survey_links_token_prefix_len
        CHECK (char_length(token_prefix) BETWEEN 8 AND 32),

    CONSTRAINT ck_survey_links_token_hash_len
        CHECK (char_length(token_hash) >= 32),

    CONSTRAINT ck_survey_links_name_len
        CHECK (char_length(btrim(name)) BETWEEN 1 AND 120),

    -- requires_auth links must be addressed to a specific email
    CONSTRAINT ck_survey_links_requires_auth_needs_assignment
        CHECK (NOT requires_auth OR assigned_email IS NOT NULL)
);

-- =========================================
-- SESSION AND RESPONSE ENCRYPTION
-- =========================================
-- Tables supporting encrypted, pseudonymous survey submission sessions.
-- See docs/session-response-encryption/ for the full design.
--
-- Notes:
-- - project_subjects is the project-level participant identity table.
-- - submission_sessions is the canonical core-side record for one survey
--   attempt. A completed submission is a completed session.
-- - response_store_id is snapshotted when the session begins so one session
--   has a stable response destination even if survey defaults change later.
-- - submission_events here is core-side analytics metadata, distinct from
--   the response-database submission_events table.

CREATE TABLE project_subjects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    pseudonymous_subject_id TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_project_subjects_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT uq_project_subjects_project_id_pseudonymous_subject_id
        UNIQUE (project_id, pseudonymous_subject_id),

    CONSTRAINT uq_project_subjects_project_id_user_id
        UNIQUE (project_id, user_id),

    CONSTRAINT ck_project_subjects_pseudonymous_subject_id_len
        CHECK (char_length(btrim(pseudonymous_subject_id)) BETWEEN 1 AND 128)
);

CREATE TABLE submission_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    survey_id BIGINT NOT NULL,
    survey_version_id BIGINT NOT NULL,
    response_store_id BIGINT NOT NULL,
    link_id BIGINT,
    project_subject_id UUID,
    browser_session_token_hash BYTEA NOT NULL,
    linkage_key_version SMALLINT NOT NULL DEFAULT 1,
    session_status TEXT NOT NULL DEFAULT 'in_progress',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_submission_sessions_browser_session_token_hash
        UNIQUE (browser_session_token_hash),

    CONSTRAINT uq_submission_sessions_id_survey_version_id
        UNIQUE (id, survey_version_id),

    CONSTRAINT ck_submission_sessions_browser_session_token_hash_len
        CHECK (length(browser_session_token_hash) >= 32),

    CONSTRAINT ck_submission_sessions_linkage_key_version_valid
        CHECK (linkage_key_version > 0),

    CONSTRAINT ck_submission_sessions_session_status_valid
        CHECK (session_status IN ('in_progress', 'completed', 'abandoned')),

    CONSTRAINT ck_submission_sessions_completed_requires_completed_at
        CHECK (session_status <> 'completed' OR completed_at IS NOT NULL),

    CONSTRAINT ck_submission_sessions_completed_at_after_started_at
        CHECK (
            completed_at IS NULL
            OR completed_at >= started_at
        ),

    CONSTRAINT ck_submission_sessions_expires_at_after_started_at
        CHECK (expires_at > started_at),

    CONSTRAINT fk_submission_sessions_survey_same_project
        FOREIGN KEY (project_id, survey_id)
        REFERENCES surveys(project_id, id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_sessions_version_same_survey
        FOREIGN KEY (survey_id, survey_version_id)
        REFERENCES survey_versions(survey_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_submission_sessions_store
        FOREIGN KEY (response_store_id)
        REFERENCES response_stores(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_submission_sessions_store_same_project
        FOREIGN KEY (project_id, response_store_id)
        REFERENCES response_stores(project_id, id),

    CONSTRAINT fk_submission_sessions_link
        FOREIGN KEY (link_id)
        REFERENCES survey_links(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_submission_sessions_link_same_survey
        FOREIGN KEY (survey_id, link_id)
        REFERENCES survey_links(survey_id, id),

    CONSTRAINT fk_submission_sessions_project_subject
        FOREIGN KEY (project_subject_id)
        REFERENCES project_subjects(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_submission_sessions_project_subject_same_project
        FOREIGN KEY (project_id, project_subject_id)
        REFERENCES project_subjects(project_id, id)
);

CREATE TABLE submission_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL,
    survey_version_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    question_node_id UUID,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_submission_events_event_type_valid
        CHECK (event_type IN ('session_started', 'question_viewed', 'answer_saved', 'session_completed')),

    CONSTRAINT ck_submission_events_question_required_for_question_events
        CHECK (
            event_type NOT IN ('question_viewed', 'answer_saved')
            OR question_node_id IS NOT NULL
        ),

    CONSTRAINT ck_submission_events_question_absent_for_session_events
        CHECK (
            event_type NOT IN ('session_started', 'session_completed')
            OR question_node_id IS NULL
        ),

    CONSTRAINT fk_submission_events_session_version
        FOREIGN KEY (session_id, survey_version_id)
        REFERENCES submission_sessions(id, survey_version_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_events_question_node
        FOREIGN KEY (question_node_id)
        REFERENCES survey_questions(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_submission_events_question_node_same_version
        FOREIGN KEY (survey_version_id, question_node_id)
        REFERENCES survey_questions(survey_version_id, id)
);

-- =========================================
-- AUDIT LOG
-- =========================================

CREATE TABLE audit_logs (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_audit_logs_metadata_is_object
        CHECK (metadata IS NULL OR jsonb_typeof(metadata) = 'object')
);

-- =========================================
-- TRIGGERS
-- =========================================

CREATE TRIGGER trg_response_stores_updated_at
BEFORE UPDATE ON response_stores
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_surveys_updated_at
BEFORE UPDATE ON surveys
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_surveys_validate_published_version
BEFORE INSERT OR UPDATE OF published_version_id ON surveys
FOR EACH ROW EXECUTE FUNCTION validate_survey_published_version();

CREATE TRIGGER trg_survey_versions_updated_at
BEFORE UPDATE ON survey_versions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_survey_versions_protect_active_published_version
BEFORE UPDATE OR DELETE ON survey_versions
FOR EACH ROW EXECUTE FUNCTION protect_active_published_version();

CREATE TRIGGER trg_survey_questions_updated_at
BEFORE UPDATE ON survey_questions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_survey_questions_lock_published
BEFORE INSERT OR UPDATE OR DELETE ON survey_questions
FOR EACH ROW EXECUTE FUNCTION prevent_changes_to_published_version_parts();


CREATE TRIGGER trg_survey_scoring_rules_updated_at
BEFORE UPDATE ON survey_scoring_rules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_survey_scoring_rules_lock_published
BEFORE INSERT OR UPDATE OR DELETE ON survey_scoring_rules
FOR EACH ROW EXECUTE FUNCTION prevent_changes_to_published_version_parts();

-- =========================================
-- INDEXES
-- =========================================

CREATE INDEX idx_project_memberships_user ON project_memberships(user_id);
CREATE INDEX idx_project_memberships_project ON project_memberships(project_id);
CREATE INDEX idx_project_memberships_role ON project_memberships(role_id);

CREATE INDEX idx_response_stores_project ON response_stores(project_id);

CREATE INDEX idx_surveys_project ON surveys(project_id);
CREATE INDEX idx_surveys_slug ON surveys(public_slug);
CREATE INDEX idx_surveys_default_response_store ON surveys(default_response_store_id);
CREATE INDEX idx_surveys_published_version ON surveys(published_version_id);

CREATE INDEX idx_survey_versions_survey ON survey_versions(survey_id);
CREATE INDEX idx_survey_versions_status ON survey_versions(status);
CREATE INDEX idx_survey_questions_version ON survey_questions(survey_version_id);
CREATE INDEX idx_survey_scoring_rules_version ON survey_scoring_rules(survey_version_id);

CREATE INDEX idx_survey_membership_roles_project ON survey_membership_roles(project_id);
CREATE INDEX idx_survey_membership_roles_membership ON survey_membership_roles(membership_id);
CREATE INDEX idx_survey_membership_roles_role ON survey_membership_roles(role_id);

CREATE INDEX idx_survey_links_survey ON survey_links(survey_id);
CREATE INDEX idx_survey_links_prefix ON survey_links(token_prefix);
CREATE INDEX idx_survey_links_hash ON survey_links(token_hash);

CREATE INDEX idx_project_subjects_project ON project_subjects(project_id);
CREATE INDEX idx_project_subjects_user ON project_subjects(user_id);

CREATE INDEX idx_submission_sessions_project ON submission_sessions(project_id);
CREATE INDEX idx_submission_sessions_survey ON submission_sessions(survey_id);
CREATE INDEX idx_submission_sessions_survey_version ON submission_sessions(survey_version_id);
CREATE INDEX idx_submission_sessions_store ON submission_sessions(response_store_id);
CREATE INDEX idx_submission_sessions_link ON submission_sessions(link_id);
CREATE INDEX idx_submission_sessions_project_subject ON submission_sessions(project_subject_id);
CREATE INDEX idx_submission_sessions_last_activity ON submission_sessions(session_status, last_activity_at);
CREATE INDEX idx_submission_sessions_expires_at ON submission_sessions(expires_at);

CREATE INDEX idx_submission_events_session_received_at ON submission_events(session_id, received_at);
CREATE INDEX idx_submission_events_survey_version ON submission_events(survey_version_id);
CREATE INDEX idx_submission_events_question_node ON submission_events(question_node_id);

CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
