-- =========================================
-- FLOWFORM CORE DATABASE SCHEMA (TIGHTENED)
-- =========================================
-- Stores core app data only; raw answers stay out of this DB.

-- =========================================
-- HELPERS
-- =========================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION prevent_changes_to_published_version_parts()
RETURNS TRIGGER AS $$
DECLARE
    v_survey_version_id BIGINT;
BEGIN
    v_survey_version_id := COALESCE(NEW.survey_version_id, OLD.survey_version_id);

    IF EXISTS (
        SELECT 1
        FROM survey_versions sv
        WHERE sv.id = v_survey_version_id
          AND sv.status = 'published'
          AND sv.deleted_at IS NULL
    ) THEN
        RAISE EXCEPTION 'Cannot modify components of a published survey version';
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_survey_published_version()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.published_version_id IS NULL THEN
        RETURN NEW;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM survey_versions sv
        WHERE sv.id = NEW.published_version_id
          AND sv.survey_id = NEW.id
          AND sv.status = 'published'
          AND sv.deleted_at IS NULL
    ) THEN
        RAISE EXCEPTION 'published_version_id must reference a published, non-deleted version of the same survey';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION protect_active_published_version()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM surveys s
        WHERE s.published_version_id = OLD.id
    ) THEN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'Cannot delete the active published survey version while it is referenced by surveys.published_version_id';
        END IF;

        IF NEW.status <> 'published' OR NEW.deleted_at IS NOT NULL THEN
            RAISE EXCEPTION 'Cannot unpublish or soft delete the active published survey version while it is referenced by surveys.published_version_id';
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION jsonb_has_exact_keys(doc jsonb, expected_keys text[])
RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT
        jsonb_typeof(doc) = 'object'
        AND doc ?& expected_keys
        AND (
            SELECT count(*)
            FROM jsonb_object_keys(doc)
        ) = (
            SELECT count(DISTINCT k)
            FROM unnest(expected_keys) AS t(k)
        );
$$;
-- =========================================
-- USERS
-- =========================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth0_user_id TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    platform_admin BOOLEAN NOT NULL DEFAULT FALSE,
    public_id TEXT NOT NULL DEFAULT (translate(encode(gen_random_bytes(6), 'base64'), '+/', '-_')) UNIQUE,

    CONSTRAINT ck_users_platform_admin CHECK (NOT platform_admin OR id = 1),
    CONSTRAINT ck_users_public_id_format CHECK (public_id ~ '^[A-Za-z0-9_-]{8}$'),
    CONSTRAINT ck_users_email_normalized
        CHECK (
            email = lower(btrim(email))
            AND char_length(email) BETWEEN 3 AND 320
        ),
    CONSTRAINT uq_users_id_email UNIQUE (id, email)
);

-- =========================================
-- PROJECTS
-- =========================================

CREATE TABLE projects (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================
-- PERMISSIONS
-- =========================================

CREATE TABLE permissions (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- =========================================
-- PROJECT ROLES
-- =========================================

CREATE TABLE project_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    is_system_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_project_roles_project_id_id
        UNIQUE (project_id, id),
    CONSTRAINT uq_project_roles_project_name
        UNIQUE (project_id, name),
    CONSTRAINT ck_project_roles_description_len
        CHECK (description IS NULL OR char_length(btrim(description)) BETWEEN 1 AND 500)
);

CREATE TABLE project_role_permissions (
    role_id BIGINT NOT NULL REFERENCES project_roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- =========================================
-- PROJECT MEMBERSHIPS
-- =========================================
CREATE TABLE project_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES project_roles (id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_project_memberships_status_valid CHECK (
        status IN ('active', 'suspended')
    ),
    CONSTRAINT uq_project_memberships_user_project UNIQUE (user_id, project_id),
    CONSTRAINT uq_project_memberships_project_id_id UNIQUE (project_id, id),
    CONSTRAINT fk_project_memberships_role_same_project FOREIGN KEY (project_id, role_id) REFERENCES project_roles (project_id, id)
);

-- =========================================
-- PROJECT INVITATIONS
-- =========================================

CREATE TABLE project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    invited_email TEXT NOT NULL,
    role_id BIGINT REFERENCES project_roles (id) ON DELETE SET NULL,
    invited_by_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    invite_message TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMPTZ,
    accepted_by_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    accepted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_project_invitations_status_valid
        CHECK (status IN ('pending', 'accepted', 'declined', 'revoked')),

    -- partial unique: only one pending invite per email per project
    -- (accepted/declined/revoked rows are kept for history and don't block re-invite)

    CONSTRAINT fk_project_invitations_role_same_project
        FOREIGN KEY (project_id, role_id)
        REFERENCES project_roles (project_id, id),

    CONSTRAINT ck_project_invitations_email_len
        CHECK (char_length(btrim(invited_email)) BETWEEN 1 AND 254),

    CONSTRAINT ck_project_invitations_message_len
        CHECK (invite_message IS NULL OR char_length(btrim(invite_message)) BETWEEN 1 AND 500),

    CONSTRAINT ck_project_invitations_accepted_fields
        CHECK (
            status <> 'accepted'
            OR (accepted_by_user_id IS NOT NULL AND accepted_at IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_project_invitations_pending_project_email
    ON project_invitations (project_id, invited_email)
    WHERE status = 'pending';

CREATE INDEX ix_project_invitations_project ON project_invitations(project_id);
CREATE INDEX ix_project_invitations_email ON project_invitations(invited_email);
CREATE INDEX ix_project_invitations_status ON project_invitations(status);

-- =========================================
-- RESPONSE STORES
-- =========================================
-- Response destinations; external credentials live in secrets.

CREATE TABLE response_stores (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    store_type TEXT NOT NULL,
    connection_reference JSONB NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_response_stores_store_type_valid
        CHECK (store_type IN ('platform_postgres', 'external_postgres')),

    CONSTRAINT ck_response_stores_connection_reference_is_object
        CHECK (jsonb_typeof(connection_reference) = 'object'),

    CONSTRAINT uq_response_stores_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT uq_response_stores_project_id_name
        UNIQUE (project_id, name)
);

-- =========================================
-- SURVEYS
-- =========================================

CREATE TABLE surveys (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'private',
    public_slug TEXT UNIQUE,
    default_response_store_id BIGINT,
    published_version_id BIGINT,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_surveys_visibility_valid
        CHECK (visibility IN ('private', 'link_only', 'public')),

    CONSTRAINT ck_surveys_public_requires_slug
        CHECK (
            visibility <> 'public'
            OR public_slug IS NOT NULL
        ),

    CONSTRAINT ck_surveys_slug_requires_public_visibility
        CHECK (
            public_slug IS NULL
            OR visibility = 'public'
        ),

    CONSTRAINT uq_surveys_project_id_id
        UNIQUE (project_id, id),
    CONSTRAINT fk_surveys_default_store
        FOREIGN KEY (default_response_store_id)
        REFERENCES response_stores(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_surveys_default_store_same_project
        FOREIGN KEY (project_id, default_response_store_id)
        REFERENCES response_stores(project_id, id)
);

-- =========================================
-- SURVEY VERSIONS
-- =========================================
-- Published compiled_schema snapshots are soft-deleted.

CREATE TABLE survey_versions (
    id BIGSERIAL PRIMARY KEY,
    survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    compiled_schema JSONB,
    published_at TIMESTAMPTZ,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT ck_survey_versions_status_valid
        CHECK (status IN ('draft', 'published', 'archived')),

    CONSTRAINT ck_survey_versions_version_number_positive
        CHECK (version_number > 0),

    CONSTRAINT ck_survey_versions_published_requires_schema_and_timestamp
        CHECK (
            status <> 'published'
            OR (compiled_schema IS NOT NULL AND published_at IS NOT NULL)
        ),

    CONSTRAINT uq_survey_versions_survey_id_id
        UNIQUE (survey_id, id),

    CONSTRAINT uq_survey_versions_survey_id_version_number
        UNIQUE (survey_id, version_number)
);

-- Added after survey_versions exists; SET NULL only clears published_version_id.
ALTER TABLE surveys
ADD CONSTRAINT fk_surveys_published_version_same_survey
    FOREIGN KEY (id, published_version_id)
    REFERENCES survey_versions(survey_id, id)
    ON DELETE SET NULL (published_version_id);

CREATE UNIQUE INDEX uq_survey_versions_one_published
    ON survey_versions (survey_id)
    WHERE status = 'published' AND deleted_at IS NULL;

-- =========================================
-- SURVEY QUESTIONS
-- =========================================

CREATE TABLE survey_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    survey_version_id BIGINT NOT NULL
        REFERENCES survey_versions(id)
        ON DELETE CASCADE,

    question_key TEXT NOT NULL,
    sort_key INTEGER NOT NULL,
    node_type TEXT NOT NULL,
    question_schema JSONB NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_survey_questions_node_type_valid
        CHECK (node_type IN ('question', 'rule')),

    CONSTRAINT ck_survey_questions_sort_key_positive
        CHECK (sort_key > 0),

    CONSTRAINT ck_survey_questions_question_key_len
        CHECK (length(question_key) BETWEEN 1 AND 128),

    CONSTRAINT ck_survey_questions_question_key_format
        CHECK (question_key ~ '^[A-Za-z0-9_-]+$'),

    CONSTRAINT ck_survey_questions_schema_size
        CHECK (length(question_schema::text) <= 10000),

    CONSTRAINT ck_survey_questions_question_schema_is_object
        CHECK (
            node_type <> 'question'
            OR jsonb_typeof(question_schema) = 'object'
        ),

    CONSTRAINT ck_survey_questions_question_family_valid
        CHECK (
            node_type <> 'question'
            OR question_schema->>'family' IN ('choice', 'field', 'matching', 'rating')
        ),

    CONSTRAINT uq_survey_questions_survey_version_id_id
        UNIQUE (survey_version_id, id)
);

CREATE UNIQUE INDEX uq_survey_questions_survey_version_id_question_key
    ON survey_questions (survey_version_id, question_key);

CREATE UNIQUE INDEX uq_survey_questions_survey_version_id_sort_key
    ON survey_questions (survey_version_id, sort_key);

CREATE INDEX ix_survey_questions_survey_version_id_node_type
    ON survey_questions (survey_version_id, node_type);

CREATE INDEX ix_survey_questions_survey_version_id_sort_key
    ON survey_questions (survey_version_id, sort_key);

-- =========================================
-- SURVEY RULES
-- =========================================


-- =========================================
-- SURVEY SCORING RULES
-- =========================================

CREATE TABLE survey_scoring_rules (
    id BIGSERIAL PRIMARY KEY,
    survey_version_id BIGINT NOT NULL REFERENCES survey_versions(id) ON DELETE CASCADE,
    scoring_key TEXT NOT NULL,
    scoring_schema JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_survey_scoring_rules_survey_version_id_scoring_key
        UNIQUE (survey_version_id, scoring_key),

    CONSTRAINT ck_survey_scoring_rules_scoring_schema_is_object
        CHECK (jsonb_typeof(scoring_schema) = 'object'),

    CONSTRAINT ck_survey_scoring_rules_scoring_schema_required_keys_present
        CHECK (scoring_schema ?& ARRAY['target', 'bucket', 'strategy', 'config']),

    CONSTRAINT ck_survey_scoring_rules_scoring_target_valid
        CHECK (
            jsonb_typeof(scoring_schema->'target') = 'string'
            AND btrim(scoring_schema->>'target') <> ''
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_bucket_valid
        CHECK (
            jsonb_typeof(scoring_schema->'bucket') = 'string'
            AND btrim(scoring_schema->>'bucket') <> ''
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_strategy_valid
        CHECK (
            scoring_schema->>'strategy' IN (
                'choice_option_map',
                'matching_answer_key',
                'rating_direct',
                'field_numeric_ranges'
            )
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_config_is_object
        CHECK (
            jsonb_typeof(scoring_schema->'config') = 'object'
        ),

    CONSTRAINT ck_survey_scoring_rules_scoring_condition_is_object
        CHECK (
            (scoring_schema ? 'condition') = FALSE
            OR jsonb_typeof(scoring_schema->'condition') = 'object'
        )
);

-- =========================================
-- SURVEY ROLES (OVERRIDE MODEL)
-- =========================================

CREATE TABLE survey_roles (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_survey_roles_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT uq_survey_roles_project_id_name
        UNIQUE (project_id, name),

    CONSTRAINT ck_survey_roles_description_len
        CHECK (description IS NULL OR char_length(btrim(description)) BETWEEN 1 AND 500)
);

CREATE TABLE survey_role_permissions (
    role_id BIGINT NOT NULL REFERENCES survey_roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE survey_membership_roles (
    project_id BIGINT NOT NULL,
    survey_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (survey_id, membership_id),
    CONSTRAINT fk_survey_membership_roles_survey_same_project
        FOREIGN KEY (project_id, survey_id)
        REFERENCES surveys(project_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_survey_membership_roles_membership_same_project
        FOREIGN KEY (project_id, membership_id)
        REFERENCES project_memberships(project_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_survey_membership_roles_role_same_project
        FOREIGN KEY (project_id, role_id)
        REFERENCES survey_roles(project_id, id)
        ON DELETE CASCADE
);

-- =========================================
-- SESSION AND RESPONSE ENCRYPTION
-- =========================================
-- Pseudonymous session tables; see docs/session-response-encryption/.

CREATE TABLE project_subjects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    project_id BIGINT NOT NULL
        REFERENCES projects(id) ON DELETE CASCADE,

    subject_code TEXT NOT NULL,

    -- If null, this row is the canonical subject.
    -- If set, this row is an alias/merged subject pointing to the canonical subject.
    canonical_subject_id UUID NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_project_subjects_project_id_id
        UNIQUE (project_id, id),

    -- Project-scoped pseudonymous participant code.
    CONSTRAINT uq_project_subjects_project_id_subject_code
        UNIQUE (project_id, subject_code),

    CONSTRAINT ck_project_subjects_subject_code_len
        CHECK (
            subject_code = btrim(subject_code)
            AND char_length(subject_code) BETWEEN 1 AND 128
        ),

    CONSTRAINT ck_project_subjects_not_self_canonical
        CHECK (
            canonical_subject_id IS NULL
            OR canonical_subject_id <> id
        ),

    CONSTRAINT fk_project_subjects_canonical_subject
        FOREIGN KEY (project_id, canonical_subject_id)
        REFERENCES project_subjects(project_id, id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_project_subjects_canonical_subject_id
    ON project_subjects(project_id, canonical_subject_id)
    WHERE canonical_subject_id IS NOT NULL;
-- Revocable identities for known subjects.
CREATE TABLE project_subject_identities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    project_subject_id UUID NOT NULL,

    identity_type TEXT NOT NULL,

    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,

    normalized_email TEXT,

    verification_status TEXT NOT NULL DEFAULT 'unverified',
    verified_at TIMESTAMPTZ,
    attached_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ,

    -- Composite UNIQUE so project_participants can prove its identity belongs
    -- to its subject (within the same project) via a same-subject composite FK.
    CONSTRAINT uq_project_subject_identities_project_subject_id
        UNIQUE (project_id, project_subject_id, id),

    CONSTRAINT fk_project_subject_identities_subject_same_project
        FOREIGN KEY (project_id, project_subject_id)
        REFERENCES project_subjects(project_id, id)
        ON DELETE CASCADE,

    CONSTRAINT fk_project_subject_identities_user_email_matches
        FOREIGN KEY (user_id, normalized_email)
        REFERENCES users(id, email)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT ck_project_subject_identities_identity_type_valid
        CHECK (identity_type IN ('email', 'authenticated_user')),

    CONSTRAINT ck_project_subject_identities_identity_value_valid
        CHECK (
            (
                identity_type = 'email'
                AND normalized_email IS NOT NULL
                AND user_id IS NULL
            )
            OR
            (
                identity_type = 'authenticated_user'
                AND user_id IS NOT NULL
                AND normalized_email IS NOT NULL
            )
        ),

    CONSTRAINT ck_project_subject_identities_verification_status_valid
        CHECK (verification_status IN ('unverified', 'verified')),

    CONSTRAINT ck_project_subject_identities_verified_at_consistent
        CHECK ((verification_status = 'verified') = (verified_at IS NOT NULL)),

    CONSTRAINT ck_project_subject_identities_normalized_email_valid
        CHECK (
            normalized_email IS NULL
            OR (
                normalized_email = lower(btrim(normalized_email))
                AND char_length(normalized_email) BETWEEN 3 AND 320
            )
        ),

    CONSTRAINT ck_project_subject_identities_verified_at_after_attached_at
        CHECK (
            verified_at IS NULL
            OR verified_at >= attached_at
        ),

    CONSTRAINT ck_project_subject_identities_revoked_at_after_attached_at
        CHECK (
            revoked_at IS NULL
            OR revoked_at >= attached_at
        )
);

-- One active authenticated subject per project.
CREATE UNIQUE INDEX uq_project_subject_identities_active_user
    ON project_subject_identities (project_id, user_id)
    WHERE (
        identity_type = 'authenticated_user'
        AND user_id IS NOT NULL
        AND revoked_at IS NULL
    );

-- No duplicate active email on one subject.
CREATE UNIQUE INDEX uq_project_subject_identities_subject_active_email
    ON project_subject_identities (project_subject_id, normalized_email)
    WHERE (
        identity_type = 'email'
        AND normalized_email IS NOT NULL
        AND revoked_at IS NULL
    );

-- One verified active email owner per project.
CREATE UNIQUE INDEX uq_project_subject_identities_project_verified_email
    ON project_subject_identities (project_id, normalized_email)
    WHERE (
        identity_type = 'email'
        AND normalized_email IS NOT NULL
        AND verification_status = 'verified'
        AND revoked_at IS NULL
    );

-- Reusable subject recognition tokens; raw tokens are never stored.
CREATE TABLE project_subject_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    project_subject_id UUID NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_project_subject_tokens_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_project_subject_tokens_subject_same_project
        FOREIGN KEY (project_id, project_subject_id)
        REFERENCES project_subjects(project_id, id)
        ON DELETE CASCADE,

    CONSTRAINT ck_project_subject_tokens_token_hash_format
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),

    CONSTRAINT ck_project_subject_tokens_expires_at_after_created_at
        CHECK (expires_at > created_at),

    CONSTRAINT ck_project_subject_tokens_last_used_at_after_created_at
        CHECK (
            last_used_at IS NULL
            OR last_used_at >= created_at
        ),

    CONSTRAINT ck_project_subject_tokens_revoked_at_after_created_at
        CHECK (
            revoked_at IS NULL
            OR revoked_at >= created_at
        ),

    CONSTRAINT ck_project_subject_tokens_last_used_before_revocation
        CHECK (
            revoked_at IS NULL
            OR last_used_at IS NULL
            OR last_used_at <= revoked_at
        )
);

-- =========================================
-- PROJECT PARTICIPANTS
-- =========================================
-- Defined before survey_links: an assigned link's assigned_participant_id
-- targets this table, so it must exist first.
CREATE TABLE project_participants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    project_subject_id UUID NOT NULL,
    -- A participant always carries a specific subject identity. A link's
    -- assigned email is derived from this identity by joining through the
    -- participant; it is never stored on survey_links.
    identity_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_project_participants_project_subject
        UNIQUE (project_id, project_subject_id),

    -- Composite UNIQUE so survey_links can target a participant within its
    -- project via a same-project composite FK.
    CONSTRAINT uq_project_participants_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT fk_project_participants_subject_same_project
        FOREIGN KEY (project_id, project_subject_id)
        REFERENCES project_subjects(project_id, id)
        ON DELETE CASCADE,

    -- The participant's identity must belong to the participant's subject
    -- (and the same project). This is the guarantee that lets a link reach a
    -- subject + identity through the participant alone.
    CONSTRAINT fk_project_participants_identity_same_subject
        FOREIGN KEY (project_id, project_subject_id, identity_id)
        REFERENCES project_subject_identities(project_id, project_subject_id, id)
        ON DELETE CASCADE
);

-- =========================================
-- PUBLIC LINKS
-- =========================================
-- Bearer links store token hashes only.

CREATE TABLE survey_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    survey_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    token_prefix TEXT NOT NULL,
    token_hash TEXT NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- general:       anonymous; anyone with the URL; no assigned participant.
    -- private:       no sign-in required; bearer-token possession is the proof
    --                of identity; must be assigned to a participant.
    -- authenticated: Auth0 sign-in required; must be assigned to a participant.
    link_type TEXT NOT NULL DEFAULT 'general',

    -- How the assignment was created. Always recorded, on every link:
    --   manual    — assigned by a human through the frontend.
    --   automated — created by a machine process.
    -- This is informational; it does not change which columns must be set.
    assignment_source TEXT NOT NULL,

    -- The sole assignment. A participant always resolves to a subject AND an
    -- identity (enforced on project_participants), so the link reaches both
    -- through this column alone. The assigned email is derived from the
    -- participant's identity by joining through project_participants.
    assigned_participant_id UUID,

    expires_at TIMESTAMPTZ,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_survey_links_token_hash
        UNIQUE (token_hash),

    CONSTRAINT uq_survey_links_survey_id_id
        UNIQUE (survey_id, id),

    CONSTRAINT uq_survey_links_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT uq_survey_links_survey_id_token_prefix
        UNIQUE (survey_id, token_prefix),

    CONSTRAINT fk_survey_links_survey_same_project
        FOREIGN KEY (project_id, survey_id)
        REFERENCES surveys(project_id, id)
        ON DELETE CASCADE,

    -- Assigned participant must belong to the link's project. RESTRICT is
    -- intentional: do not silently turn an assigned link into a general one.
    CONSTRAINT fk_survey_links_assigned_participant_same_project
        FOREIGN KEY (project_id, assigned_participant_id)
        REFERENCES project_participants(project_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_survey_links_token_prefix_len
        CHECK (char_length(token_prefix) BETWEEN 8 AND 32),

    CONSTRAINT ck_survey_links_token_hash_format
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),

    CONSTRAINT ck_survey_links_name_len
        CHECK (char_length(btrim(name)) BETWEEN 1 AND 120),

    CONSTRAINT ck_survey_links_link_type_valid
        CHECK (link_type IN ('general', 'private', 'authenticated')),

    -- Always recorded, regardless of link_type or whether a participant is set.
    CONSTRAINT ck_survey_links_assignment_source_valid
        CHECK (assignment_source IN ('manual', 'automated')),

    -- A general link carries no assigned participant.
    CONSTRAINT ck_survey_links_general_has_no_assignment
        CHECK (
            link_type <> 'general'
            OR assigned_participant_id IS NULL
        ),

    -- A private or authenticated link must be assigned to a participant.
    CONSTRAINT ck_survey_links_assigned_requires_participant
        CHECK (
            link_type = 'general'
            OR assigned_participant_id IS NOT NULL
        ),

    -- Single-use is derived from carrying a participant assignment.
    CONSTRAINT ck_survey_links_used_at_requires_assignment
        CHECK (
            used_at IS NULL
            OR assigned_participant_id IS NOT NULL
        )
);

CREATE TABLE submission_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    survey_id BIGINT NOT NULL,
    survey_version_id BIGINT NOT NULL,
    response_store_id BIGINT NOT NULL REFERENCES response_stores(id) ON DELETE RESTRICT,
    link_id UUID REFERENCES survey_links(id) ON DELETE SET NULL,
    project_subject_id UUID REFERENCES project_subjects(id) ON DELETE SET NULL,
    browser_session_token_hash BYTEA NOT NULL,
    linkage_key_version SMALLINT NOT NULL DEFAULT 1,
    session_status TEXT NOT NULL DEFAULT 'in_progress',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_submission_sessions_browser_session_token_hash
        UNIQUE (browser_session_token_hash),

    CONSTRAINT uq_submission_sessions_id_survey_version_id
        UNIQUE (id, survey_version_id),

    CONSTRAINT uq_submission_sessions_project_id_id
        UNIQUE (project_id, id),

    CONSTRAINT uq_submission_sessions_id_project_subject_id
        UNIQUE (id, project_subject_id),

    CONSTRAINT ck_submission_sessions_browser_session_token_hash_len
        CHECK (length(browser_session_token_hash) >= 32),

    CONSTRAINT ck_submission_sessions_linkage_key_version_valid
        CHECK (linkage_key_version > 0),

    CONSTRAINT ck_submission_sessions_session_status_valid
        CHECK (session_status IN ('in_progress', 'completed', 'abandoned')),

    CONSTRAINT ck_submission_sessions_completed_at_consistent
        CHECK ((session_status = 'completed') = (completed_at IS NOT NULL)),

    CONSTRAINT ck_submission_sessions_completed_at_after_started_at
        CHECK (
            completed_at IS NULL
            OR completed_at >= started_at
        ),

    CONSTRAINT ck_submission_sessions_expires_at_after_started_at
        CHECK (expires_at > started_at),

    CONSTRAINT ck_submission_sessions_last_activity_at_after_started_at
        CHECK (last_activity_at >= started_at),

    CONSTRAINT ck_submission_sessions_completed_before_last_activity
        CHECK (
            completed_at IS NULL
            OR completed_at <= last_activity_at
        ),

    CONSTRAINT fk_submission_sessions_survey_same_project
        FOREIGN KEY (project_id, survey_id)
        REFERENCES surveys(project_id, id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_sessions_version_same_survey
        FOREIGN KEY (survey_id, survey_version_id)
        REFERENCES survey_versions(survey_id, id)
        ON DELETE RESTRICT,


    CONSTRAINT fk_submission_sessions_store_same_project
        FOREIGN KEY (project_id, response_store_id)
        REFERENCES response_stores(project_id, id),


    CONSTRAINT fk_submission_sessions_link_same_survey
        FOREIGN KEY (survey_id, link_id)
        REFERENCES survey_links(survey_id, id),


    CONSTRAINT fk_submission_sessions_project_subject_same_project
        FOREIGN KEY (project_id, project_subject_id)
        REFERENCES project_subjects(project_id, id)
);

CREATE TABLE submission_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL,
    survey_version_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    question_node_id UUID REFERENCES survey_questions(id) ON DELETE SET NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_submission_events_event_type_valid
        CHECK (event_type IN ('session_started', 'question_viewed', 'answer_saved', 'session_completed')),

    CONSTRAINT ck_submission_events_question_required_for_question_events
        CHECK (
            event_type NOT IN ('question_viewed', 'answer_saved')
            OR question_node_id IS NOT NULL
        ),

    CONSTRAINT ck_submission_events_question_absent_for_session_events
        CHECK (
            event_type NOT IN ('session_started', 'session_completed')
            OR question_node_id IS NULL
        ),

    CONSTRAINT fk_submission_events_session_version
        FOREIGN KEY (session_id, survey_version_id)
        REFERENCES submission_sessions(id, survey_version_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_events_question_node_same_version
        FOREIGN KEY (survey_version_id, question_node_id)
        REFERENCES survey_questions(survey_version_id, id)
);

-- =========================================
-- SUBJECT IP OBSERVATIONS
-- =========================================
-- Identifying core metadata; never copied to the response DB.

CREATE TABLE subject_ip_observations (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

    project_subject_id UUID REFERENCES project_subjects(id) ON DELETE CASCADE,
    submission_session_id UUID REFERENCES submission_sessions(id) ON DELETE CASCADE,

    ip_address INET NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_subject_ip_observations_has_owner
        CHECK (
            project_subject_id IS NOT NULL
            OR submission_session_id IS NOT NULL
        ),

    CONSTRAINT fk_subject_ip_observations_subject_same_project
        FOREIGN KEY (project_id, project_subject_id)
        REFERENCES project_subjects(project_id, id),

    CONSTRAINT fk_subject_ip_observations_session_same_project
        FOREIGN KEY (project_id, submission_session_id)
        REFERENCES submission_sessions(project_id, id),

    -- If both are present, subject and session must match.
    CONSTRAINT fk_subject_ip_observations_session_subject_match
        FOREIGN KEY (submission_session_id, project_subject_id)
        REFERENCES submission_sessions(id, project_subject_id)
);

-- =========================================
-- AUDIT LOG
-- =========================================
CREATE TABLE subject_logs (
    id BIGSERIAL PRIMARY KEY,
    project_subject_id UUID REFERENCES project_subjects(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_subject_logs_metadata_is_object
        CHECK (metadata IS NULL OR jsonb_typeof(metadata) = 'object')
);

CREATE TABLE audit_logs (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_audit_logs_metadata_is_object
        CHECK (metadata IS NULL OR jsonb_typeof(metadata) = 'object')
);

-- =========================================
-- TRIGGERS
-- =========================================

CREATE TRIGGER trg_response_stores_updated_at
BEFORE UPDATE ON response_stores
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_surveys_updated_at
BEFORE UPDATE ON surveys
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_surveys_validate_published_version
BEFORE INSERT OR UPDATE OF published_version_id ON surveys
FOR EACH ROW EXECUTE FUNCTION validate_survey_published_version();

CREATE TRIGGER trg_survey_versions_updated_at
BEFORE UPDATE ON survey_versions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_survey_versions_protect_active_published_version
BEFORE UPDATE OR DELETE ON survey_versions
FOR EACH ROW EXECUTE FUNCTION protect_active_published_version();

CREATE TRIGGER trg_survey_questions_updated_at
BEFORE UPDATE ON survey_questions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_survey_questions_lock_published
BEFORE INSERT OR UPDATE OR DELETE ON survey_questions
FOR EACH ROW EXECUTE FUNCTION prevent_changes_to_published_version_parts();


CREATE TRIGGER trg_survey_scoring_rules_updated_at
BEFORE UPDATE ON survey_scoring_rules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_survey_scoring_rules_lock_published
BEFORE INSERT OR UPDATE OR DELETE ON survey_scoring_rules
FOR EACH ROW EXECUTE FUNCTION prevent_changes_to_published_version_parts();

-- =========================================
-- INDEXES
-- =========================================

CREATE INDEX ix_project_memberships_user ON project_memberships(user_id);
CREATE INDEX ix_project_memberships_project ON project_memberships(project_id);
CREATE INDEX ix_project_memberships_role ON project_memberships(role_id);

CREATE INDEX ix_response_stores_project ON response_stores(project_id);

CREATE INDEX ix_surveys_project ON surveys(project_id);
CREATE INDEX ix_surveys_slug ON surveys(public_slug);
CREATE INDEX ix_surveys_default_response_store ON surveys(default_response_store_id);
CREATE INDEX ix_surveys_published_version ON surveys(published_version_id);

CREATE INDEX ix_survey_versions_survey ON survey_versions(survey_id);
CREATE INDEX ix_survey_versions_status ON survey_versions(status);
CREATE INDEX ix_survey_questions_version ON survey_questions(survey_version_id);
CREATE INDEX ix_survey_scoring_rules_version ON survey_scoring_rules(survey_version_id);

CREATE INDEX ix_survey_membership_roles_project ON survey_membership_roles(project_id);
CREATE INDEX ix_survey_membership_roles_membership ON survey_membership_roles(membership_id);
CREATE INDEX ix_survey_membership_roles_role ON survey_membership_roles(role_id);

CREATE INDEX ix_survey_links_survey ON survey_links(survey_id);
CREATE INDEX ix_survey_links_project ON survey_links(project_id);
CREATE INDEX ix_survey_links_prefix ON survey_links(token_prefix);
CREATE INDEX ix_survey_links_assigned_participant ON survey_links(assigned_participant_id)
    WHERE assigned_participant_id IS NOT NULL;
CREATE INDEX ix_survey_links_active_expiry ON survey_links(expires_at)
    WHERE is_active = TRUE;

CREATE INDEX ix_project_subjects_project ON project_subjects(project_id);

CREATE INDEX ix_project_subject_identities_subject ON project_subject_identities(project_subject_id);
CREATE INDEX ix_project_subject_identities_user ON project_subject_identities(user_id)
    WHERE user_id IS NOT NULL;
CREATE INDEX ix_project_subject_identities_email ON project_subject_identities(normalized_email)
    WHERE normalized_email IS NOT NULL;

CREATE INDEX ix_project_subject_tokens_subject ON project_subject_tokens(project_subject_id);
CREATE INDEX ix_project_subject_tokens_active_expiry ON project_subject_tokens(expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX ix_submission_sessions_project ON submission_sessions(project_id);
CREATE INDEX ix_submission_sessions_survey ON submission_sessions(survey_id);
CREATE INDEX ix_submission_sessions_survey_version ON submission_sessions(survey_version_id);
CREATE INDEX ix_submission_sessions_store ON submission_sessions(response_store_id);
CREATE INDEX ix_submission_sessions_link ON submission_sessions(link_id)
    WHERE link_id IS NOT NULL;
CREATE INDEX ix_submission_sessions_project_subject ON submission_sessions(project_subject_id)
    WHERE project_subject_id IS NOT NULL;
CREATE INDEX ix_submission_sessions_last_activity ON submission_sessions(session_status, last_activity_at);
CREATE INDEX ix_submission_sessions_expires_at ON submission_sessions(expires_at);

CREATE INDEX ix_submission_events_session_received_at ON submission_events(session_id, received_at);
CREATE INDEX ix_submission_events_survey_version ON submission_events(survey_version_id);
CREATE INDEX ix_submission_events_question_node ON submission_events(question_node_id)
    WHERE question_node_id IS NOT NULL;

CREATE INDEX ix_subject_ip_observations_project_observed_at
    ON subject_ip_observations(project_id, observed_at DESC);
CREATE INDEX ix_subject_ip_observations_subject_observed_at
    ON subject_ip_observations(project_subject_id, observed_at DESC)
    WHERE project_subject_id IS NOT NULL;
CREATE INDEX ix_subject_ip_observations_session_observed_at
    ON subject_ip_observations(submission_session_id, observed_at DESC)
    WHERE submission_session_id IS NOT NULL;
CREATE INDEX ix_subject_ip_observations_ip_observed_at
    ON subject_ip_observations(ip_address, observed_at DESC);

CREATE INDEX ix_audit_logs_entity ON audit_logs(entity_type, entity_id);
