\set ON_ERROR_STOP on \connect ${FF_PGDB_CORE__DB_NAME}

GRANT USAGE ON SCHEMA core_app TO ${FF_PGDB_CORE__APP_USER};

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA core_app
TO ${FF_PGDB_CORE__APP_USER};

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA core_app
TO ${FF_PGDB_CORE__APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE flowform_owner IN SCHEMA core_app
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES
TO ${FF_PGDB_CORE__APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE flowform_owner IN SCHEMA core_app
GRANT USAGE, SELECT, UPDATE ON SEQUENCES
TO ${FF_PGDB_CORE__APP_USER};

ALTER ROLE ${FF_PGDB_CORE__APP_USER} SET search_path = core_app;